### ISSUE TITLE
Use (optionally?) inet6 transport option

### ISSUE THREAD

**Issue by sysashi** [wojtekmach/req#109]
Hi, sorry if that's a bad issue, I'm just not sure where this configuration should be on a user level or library one.

I was trying to do some requests to an ip6 host where dns nameserver is also an ip6. So `inet` could not resolve the domain.
The only thing that worked for me is to create a separate Finch instance with config

```
    %{
      default: [
        conn_opts: [
          transport_opts: [
            inet6: true
          ]
        ]
      ]
    }
```

and use it with Req.
I'm also not entirely sure ip4 connections will still work, would it fallback to use ip4? By the looks of it, it does

**Comment by wojtekmach** [comment]
Thank you for reporting it, that's definitely a limitation. Yes, currently the only way to configure connection options is to start your own Finch pool. I want to make it easier, most likely starting a pool with custom options for you, but I haven't think that through. Regarding ipv4 on ipv6, no idea.

**Comment by sysashi** [comment]
Just for the sake of interest I tried running a request against a domain with only A record configured (no AAAA) with above config, it resolves correctly to ipv4 address. Obviously it's not good enough reason for just adding this option to the Finch instance that Req starts by default, and also I practically have no knowledge how it works/suppose to work.

Either way thanks for the reply! It was _relatively_ straightforward to find right option, just needed to dive through Req -> Finch -> Mint -> inet docs :smile: but as always, everything was well documented.

p.s. thanks for the library and good docs!
