### ISSUE TITLE
Add `Req.Request` help functions

### ISSUE THREAD

**Issue by aleDsz** [wojtekmach/req#116]
- `Req.Request.merge_headers/2`:

  Adding new headers can be easy with `Req.Request.put_header/3`, but when we want to update an existing header, we don't have a useful function to do that, so this could help to update an existing header with new a value, instead of appending a value to the header, making it a list than a String.

  ```elixir
  req = Req.new() |> Req.Request.put_header("my-header", "foo")
  # => %Req.Request{..., headers: [..., {"my-header", "foo"}, ...], ...}

  req = Req.Request.merge_headers(req, [{"my-header", "var"}])
  # => %Req.Request{..., headers: [..., {"my-header", "var"}, ...], ...}
  ```

- `Req.Request.remove_private/2`:

  Thinking about removing a key from the `private` map from `Req.Request` could help to change the actual state of a step (custom or not) to keep his flow as he want to.

  ```elixir
  req = Req.new() |> Req.Request.put_private(:foo, :bar)
  # => %Req.Request{..., private: %{foo: :bar}, ...}

  req = Req.Request.remove_private(req, :foo)
  # => %Req.Request{..., private: %{}, ...}
  ```

WDYT?

**Comment by wojtekmach** [comment]
put_headers is in! Let's hold off on delete_private for now.
