### ISSUE TITLE
Question: is there a debug step?

### ISSUE THREAD

**Issue by maxxst** [wojtekmach/req#124]
Is there a way to see the outgoing `%Req.Request{}` map?

**Comment by wojtekmach** [comment]
There is not but it is easy to write one yourself. And if you would like to keep the request struct around, you can have a response that puts it into response.private.

Im going to close this but feel free to continue discussing this.

**Comment by wojtekmach** [comment]
Oh, thats a good call, that would definitely work too.

**Comment by maxxst** [comment]
Shower thought: should there be a `Req.update` ? Just like `Req.new` but it updates an existing `%Req.Request{}`.

**Comment by wojtekmach** [comment]
We have some functions for that already, e.g.: `Req.Request.put_header`, `Req.Request.merge_options`. One can of course also use Map.update!/Map.replace!. Any request field in particular you'd like to update?

**Comment by maxxst** [comment]
My use-case would be mostly debugging. So I made a `Req.request` and it does not work. I would love a quick look at the request itself and see if I did something wrong to produce a wrong `%Req.Request{}`.

The solution that popped into my mind was: "What if I can just replace `Req.request` with `Req.update` and get the `%Req.Request{}` that would be used for the request.
