### ISSUE TITLE
`follow_redirects`: Do not send authorization header on redirects to different hosts

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#13]
See `curl --locattion` and `curl --location-trusted` for more information.

**Comment by srowley** [comment]
This seemed like something a relative novice like me could do, but I got hung up trying to test requests to different hosts using Bypass, since all of those requests go to `localhost`. Would it be worth your time for me to submit a draft PR with everything but that test for review/discussion?

**Comment by wojtekmach** [comment]
Yes, please send a PR!

I think an easy way to test this behaviour is by not actually hitting the network. We can do that by having an _adapter_ with canned responses:

```elixir
    adapter = fn request ->
      case request.url.host do
        "host1" ->
          assert List.keyfind(request.headers, "authorization", 0)

          response = %Req.Response{
            status: 301,
            headers: [{"location", "http://host2"}],
            body: "redirecting"
          }

          {request, response}

        "host2" ->
          refute List.keyfind(request.headers, "authorization", 0)

          response = %Req.Response{
            status: 200,
            headers: [],
            body: "host2"
          }

          {request, response}
      end
    end

    response =
      Req.Request.build(:get, "http://host1", headers: [{"authorization", "foo"}])
      |> Req.Request.append_response_steps([{Req.Steps, :follow_redirects, []}])
      |> Req.Request.put_adapter(adapter)
      |> Req.Request.run!()

    assert response.body == "host2"
```

of course this doesn't give us as much confidence as with real HTTP requests but seems warranted in this particular case. Hope this helps!
