### ISSUE TITLE
Bypass URI.encode on params

### ISSUE THREAD

**Issue by jkbbwr** [wojtekmach/req#133]
I have a route that requires `test=a,b` but when passed as a param to `Req` it converts that into `test=a%2Cb` which is wrong.

Current work around is 

```elixir
  defp put_param_unencoded(req) do
    update_in(req.url.query, fn
      nil -> "test=a,b"
      query -> query <> "&" <> "test=a,b"
    end)
  end
  
  Req.new(...)
  |> put_param_unencoded()
```

**Comment by wojtekmach** [comment]
Thank you for the report. Do you know what the spec says about encoding this character and/or how other popular HTTP clients treat it? In other words, do you have a proposal how this should work in Req?

**Comment by jkbbwr** [comment]
Actually I think I am being very very stupid. Thanks for sanity checking me.
