### ISSUE TITLE
Req failing to reconnect socket after running idle

### ISSUE THREAD

**Issue by davydog187** [wojtekmach/req#135]
What's up Wojtek! The `Req` API is great, and I've found it convenient for using in Oban. However, I've noticed particularly in iex sessions that I'll experience socket disconnections that are unable to reconnect.

```elixir
[error] retry: got exception, will retry in 1000ms, 3 attempts left
[error] ** (Mint.TransportError) socket closed
[error] retry: got exception, will retry in 2000ms, 2 attempts left
[error] ** (Mint.TransportError) socket closed
[error] retry: got exception, will retry in 4000ms, 1 attempt left
[error] ** (Mint.TransportError) socket closed
```

Happy to share more details if that's helpful. Also feel free to close as I do not have a reproduceable example

**Comment by wojtekmach** [comment]
Yeah if you could share more details (privately if you prefer) for me to reproduce it that would be very helpful.

**Comment by davydog187** [comment]
@wojtekmach let me see if i can spin up an example scenario

**Comment by wojtekmach** [comment]
any luck?

**Comment by davydog187** [comment]
Sorry Wojtek, I promise the issue exists but I haven't been able to come up with a reliable example. I'll close and reopen if that changes.
