### ISSUE TITLE
Bypass integration for tests

### ISSUE THREAD

**Issue by torepettersen** [wojtekmach/req#137]
I would like to integrate `Req` with Bypass for tests. Seems like it should be possible to add a step. Maybe something like `Req.default_options/1`, just that it has to override base_url instead of being a fallback.

So ideal for me would be something like:
```elixir
bypass = Bypass.open()
Req.bypass(bypass)
bypass.port => 12345

Req.get!("/bar", base_url: "https://foo.com/")
url => http://localhost:12345/bar
```

I understand if you don't want to make Bypass a dependency, so a more generic approach would also be an idea:
```elixir
Req.test_options(base_url: "http://localhost:#{bypass.port}")

Req.get!("/bar", base_url: "https://foo.com/")
url => http://localhost:12345/bar
```

What do you think?

I would also be happy to contribute if you like the idea.

**Comment by wojtekmach** [comment]
> `base_url: "https://foo.com/")`

Given with Bypass we need to hit the network, the bypass server, this base_url is basically ignored. Thus, wouldn't this work for you?

```elixir
bypass = Bypass.open()
Req.get!("/bar", base_url: "http://localhost:#{bypass.port}")
```

You could of course provide convenience for it, a ReqBypass plugin:

```elixir
bypass = Bypass.open()

req =
  Req.new()
  |> ReqBypass.attach()

Req.get!("/bar", bypass: bypass)
```

(though honestly I'm not sure if it's a big improvement over the super straightforward one using :base_url.)

In any case, I'd avoid Req.default_options/1 and similar solutions as they are mutating global state and thus preventing tests from being async.

**Comment by torepettersen** [comment]
No, that would unfortunately not work. The request might be several layers down, so that would force me to always pass down `Req.new(base_url: "http://localhost:#{bypass.port}")` all places where it is used.

My current solution is using a mock:
```elixir
#test
def client do
  Req.new(base_url: "http://localhost:12345")
end

# dev
def client do
  Req.new(base_url: "https://foo.com")
end

client = client()
Req.get!(client, url: "/bar")
```

And in most cases it would still be possible to keep the tests async with an approach like I suggested, if we use `Process.get/2` and `Process.set/2` to store the `base_url`.

I know that would not work for tests which spawn tasks, so for cases like that we might need something like `Req.bypass_global(bypass)`. Although that would have the drawback that tests can't be async in those cases. But that is a limitation I also have when I am using a mocking library.

**Comment by wojtekmach** [comment]
Got it, thank you for extra context.

I don't plan to add Bypass integration at the moment. I don't plan to add any other global state based functionality either.

Even though the Req struct creation is perhaps deep in your code, you can still instrument it. In other words, write Req.bypass yourself. Perhaps something like this, using pdict:

```elixir
def Foo do
  def client do
    Req.new(base_url: "...")
    |> run_bypass()
  end

  if Mix.env() == :test do
    def setup_bypass(bypass) do
      Process.put(:req_bypass, bypass)
    end

    defp run_bypass(request) do
      if bypass = Process.get(:req_bypass) do
        base_url = "http://localhost:#{bypass.port}"
        put_in(request.options.base_url, base_url)
      else
        request
      end
    end
  else
    defp run_bypass(request), do: request
  end
end
```

**Comment by torepettersen** [comment]
Thanks, that would work perfectly!
