### ISSUE TITLE
More customisable cache?

### ISSUE THREAD

**Issue by thbar** [wojtekmach/req#138]
Hey @wojtekmach ; again, thanks for your work on `req`, it is a great library.

Today I tried again to use the existing cache (https://hexdocs.pm/req/Req.Steps.html#cache/1) which relies on `if-modified-since` request header, but like in the past, the servers I'm targeting do not honour it, so the cache does not work.

At this point I'm just wrapping the `get!` with custom caching code, and I've looked into writing a little plugin for that.

While looking into that, I saw that (as expected) a lot of what I will have to do will essentially replicate what's done in the cache step (https://github.com/wojtekmach/req/blob/102b9aa6c6ff66f00403054a0093c4f06f6abc2f/lib/req/steps.ex#L362-L424), with operations like creating a local file name etc.

I wonder if passing functions/hooks around could improve that, or if you feel it is out of scope for `req`?

**Comment by wojtekmach** [comment]
I haven't thought about hooks for steps. Do you have an idea how it would look like to use them? Or you didn't mean hooks in general, just hooks for cache specifically? We only have very basic cache support and thus the code is very straightforward so I'd just copy paste it. :)

**Comment by thbar** [comment]
I do not have a clear idea yet, because it was the first time I implemented a plugin. After doing it actually, I think it's probably better to accept the duplication of code for now.

Sharing it here (and I will share an article later if I find the energy, and maybe a package at some point?), in case it helps others:

```elixir
Mix.install([
  {:req, "~> 0.3.0"}
])

defmodule CustomCache do
  require Logger

  def attach(%Req.Request{} = request, options \\ []) do
    request
    |> Req.Request.register_options([:custom_cache_dir])
    |> Req.Request.merge_options(options)
    |> Req.Request.append_request_steps(custom_cache: &request_local_cache_step/1)
    |> Req.Request.prepend_response_steps(custom_cache: &response_local_cache_step/1)
  end

  def request_local_cache_step(request) do
    # TODO: handle a form of expiration - for now it is acceptable to wipe out the whole folder manually for me
    # NOTE: race condition here, for parallel queries
    if File.exists?(path = cache_path(request)) do
      Logger.info("File found in cache (#{path})")
      {request, load_cache(path)}
    else
      request
    end
  end

  def response_local_cache_step({request, response}) do
    unless File.exists?(path = cache_path(request)) do
      if response.status == 200 do
        Logger.info("Saving file to cache (#{path})")
        write_cache(path, response)
      else
        Logger.info("Status is #{response.status_code}, not saving file to disk")
      end
    end

    {request, response}
  end

  # https://github.com/wojtekmach/req/blob/102b9aa6c6ff66f00403054a0093c4f06f6abc2f/lib/req/steps.ex#L1268
  def cache_path(cache_dir, request) do
    cache_key =
      Enum.join(
        [
          request.url.host,
          Atom.to_string(request.method),
          :crypto.hash(:sha256, :erlang.term_to_binary(request.url))
          |> Base.encode16(case: :lower)
        ],
        "-"
      )

    Path.join(cache_dir, cache_key)
  end

  def cache_path(request) do
    cache_path(request.options[:custom_cache_dir], request)
  end

  # https://github.com/wojtekmach/req/blob/102b9aa6c6ff66f00403054a0093c4f06f6abc2f/lib/req/steps.ex#L1288-L1290
  def load_cache(path) do
    path |> File.read!() |> :erlang.binary_to_term()
  end

  # https://github.com/wojtekmach/req/blob/102b9aa6c6ff66f00403054a0093c4f06f6abc2f/lib/req/steps.ex#L1283-L1286
  def write_cache(path, response) do
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, :erlang.term_to_binary(response))
  end
end

defmodule Streamer do
  def cached_get!(start_url) do
    req = Req.new() |> CustomCache.attach()
    cache_dir = Path.join(__ENV__.file, "../cache-dir") |> Path.expand()
    %{body: body, status: 200} = Req.get!(req, url: start_url, custom_cache_dir: cache_dir)
    body
  end
end

url = "https://www.data.gouv.fr/api/1/datasets/?tag=irve"

Streamer.cached_get!(url)
```

I think we can go ahead and close this, but I also assume it will be useful to others (at least it will be useful very often to me!).

If I create an article, maybe you can link it? (or another form of documentation?)

**Comment by thbar** [comment]
Article created here - thanks for your great plugin architecture!

https://thibautbarrere.com/2022/09/09/implementing-a-disk-cache-for-elixir-req
