### ISSUE TITLE
`follow_redirects`: Send a GET request after a 301..303

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#14]
Currently we use the method of the original request. See `curl --location`. We should also support all the other 3xx codes provided they have the location header.

**Comment by thbar** [comment]
Just sharing my findings as I wondered about supported redirect codes (308 or not etc):

> We should also support all the other 3xx codes provided they have the location header.

Related:
- https://github.com/benoitc/hackney/issues/635
- https://github.com/edgurgel/httpoison/issues/447

For other readers (such as @fchabouis), req is at time of writing supporting this:

https://github.com/wojtekmach/req/blob/c345e5b5e4b434d7a181ccffd50e5915aecd30f7/lib/req.ex#L829

**Comment by srowley** [comment]
I would be interested in working on this one. Based on what I have found:

- [curl docs](https://curl.se/docs/manpage.html#-L)
- [MDN explanation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections)

it sounds like the desired behavior would be:

- 301..303: redirect, change method to GET
- 307..308: redirect, don't change method

Is that right?

**Comment by wojtekmach** [comment]
@srowley sounds good, please go ahead and thank you!
