### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by lamp-town-guy** [wojtekmach/req#141]
I'm writing an elixir library to communicate with an API and I've chosen this library for doing requests because I like the API. Everything works as expected but I was not able to find docs for file upload. When I've tried to look for the implementation I wasn't able to find one. `encode_body/1` didn't have `multipart/form-data` encoding. Only json and www-form. When I've looked into req-s3 library there was also no upload.

Is it something that's missing from docs or there's also implementation missing? If there are docs missing I have no problem contributing.

**Comment by wojtekmach** [comment]
We don't have file uploads yet.

**Comment by wojtekmach** [comment]
Closing in favour of #74

**Comment by samrat** [comment]
Hello! Are file uploads supported now? I couldn't find any docs that point out how to send a file as form-data.

If not, what is the alternative? Is it possible to drop down to Finch for this?

**Comment by wojtekmach** [comment]
There is still no built in support however you can use the multipart package. They have instructions for Finch and it’s easy to translate them to Req: https://github.com/breakroom/multipart#usage

**Comment by samrat** [comment]
Thanks! In case anyone else runs into the same issue, I wrote a short note on what I did: https://samrat.me/blog/til-file-uploads-using-the-req-elixir-library

**Comment by acalejos** [comment]
> Thanks! In case anyone else runs into the same issue, I wrote a short note on what I did: https://samrat.me/blog/til-file-uploads-using-the-req-elixir-library

I was looking to use this exactly for Whisper like your code snippet shows, so thanks for writing it up!

**Comment by esambo** [comment]
Looks like the new [`:form_multipart`](https://hexdocs.pm/req/Req.Steps.html#encode_body/1) option implements it (in 60253dbe9436cb8e9c738f895032f2e87939b597), and is also mentioned in [SDKs with Req: S3](https://dashbit.co/blog/sdks-with-req-s3).

But it doesn't seem to calculate the Content-Length header.

**Comment by wojtekmach** [comment]
Correct. My understanding is content-length is not strictly necessary because multipart/form-data explicitly marks the end of the data. If we don't calculate content-length we _could_ (not done yet, exactly because I don't want to paint ourselves into a corner) support any enumerable, not just %File.Stream{}, that we don't know the length of as input to :form_enumerable. If this is a deal breaker for your integration, please open up an issue with some context. Thank you!

**Comment by Rim-777** [comment]
> Thanks! In case anyone else runs into the same issue, I wrote a short note on what I did: https://samrat.me/blog/til-file-uploads-using-the-req-elixir-library

Thank you so much!!!!! @samrat, this was exactly my case

**Comment by PJUllrich** [comment]
Just FYI: I _think_ that Req supports proper `multipart/form-data` now. See https://hexdocs.pm/req/Req.Steps.html#encode_body/1-request-options

Example:
```elixir
# You can pass in a binary like this:
contents = File.read!("example.txt")

options = [
      form_multipart: [file: {contents, filename: "example.txt"}]
]

# Or, a File.Stream, though I haven't tested it.
stream = File.stream!("example.txt")

options = [
      form_multipart: [file: {stream, filename: "example.txt"}]
]

Req.post!("https://example.com", options)
```
