### ISSUE TITLE
Add @callbacks to allow mocking Req interface

### ISSUE THREAD

**Issue by AndroidOatmeal** [wojtekmach/req#143]
Hi there. I'm considering using Req for a project, however I found that there is no clean way to mock the API via the [Mox Library](https://github.com/dashbitco/mox). The ability to mock an HTTP client is important for testing various cases. The solution for this seems simple: define `@callback`s for a `ReqApi`, and have `Req` implement that behaviour.

What do you think? Thanks for your hard work.

**Comment by wojtekmach** [comment]
Hey, thank you for considering Req for your project. I'm not planning to add such ReqApi contract as it's easy enough to add it on a per-project basis. Especially that I think different projects would use different subsets of Req (e.g. just Req.request/1 function.)

FWIW in my projects I'd either introduce mocks:
- "above" Req, by having domain-specific contract e.g. MyApp.Twitter and a MyApp.Twitter.Req implementation. See https://dashbit.co/blog/mocks-and-explicit-contracts.
- "below" Req by having a mock for the network (by using [Bypass](https://github.com/PSPDFKit-labs/bypass) or built-in features of Req: :adapter and :plug options.)
