### ISSUE TITLE
FInch/Mint TLS options seem to not be exposed

### ISSUE THREAD

**Issue by jkbbwr** [wojtekmach/req#147]
I need to do MTLS with the API I am talking to and the options don't seem to be exposed at the moment for me to set them in default Req. 

I think I can work around with a custom finch but it would be nice if they could be passed down.

**Comment by wojtekmach** [comment]
Agreed. What does the configuration for finch or mint look like?

**Comment by jkbbwr** [comment]
```elixir
    children = [
      {
        Finch,
        name: MTLSFinch,
        pools: %{
          default: [
            conn_opts: [
              transport_opts: [certfile: "./certs/transport.pem", keyfile: "./certs/obwac.pem"]
            ]
          ]
        }
      }
    ]
 ```
This is the finch/pool im spawning to do the TLS myself. 

If conn_opts -> transport_opts were passed down the line it would make life nice.

Id expect to be able to make a call like
    
```elixir
Req.default_options(finch_options: [
    conn_opts: [
          transport_opts: [certfile: "./certs/transport.pem", keyfile: "./certs/obwac.pem"]
        ]
])
```

**Comment by wojtekmach** [comment]
Agreed. We already have `connect_options` so a PR that allows

```elixir
Req.new(connect_options: [transport_opts: [...]])
```

would be very appreciated. `_options` vs `_opts` is a bit awkward but that's ok, we can always deprecate the former down the road.

**Comment by jkbbwr** [comment]
Ill not be able to do this tonight, but Ill stick it on the backlog

**Comment by jkbbwr** [comment]
@wojtekmach Sorry for not submitting this myself, its been a long month.

**Comment by wojtekmach** [comment]
no worries!
