### ISSUE TITLE
How to add a step after a specific step?

### ISSUE THREAD

**Issue by Arp-G** [wojtekmach/req#148]
Hello, firstly thanks for this awesome library.

I wanted to understand how can I add my own custom step after a specific step. Currently I see the `append_request_steps/2` and `prepend_request_steps/2` functions only allow us to append or prepend a step.

My use case is to add a custom step that would take the JSON body and add a `idempotency_key` in it, I believe this has to happen before the body is encoded that is before the `encode_body(request)` step. 

Currently, the only way I can think of is like...

(**Untested code below**)
```
  def new do
    Req.new(
      base_url: @base_url,
      headers: headers(),
      auth: {:bearer, get_auth_token()},
    )
    |> Map.put(:request_steps, request_steps())
    |> Req.Request.append_response_steps(inspect: &IO.inspect/1)
  end

  defp request_steps do
    [
      put_user_agent: &Req.Steps.put_user_agent/1,
      compressed: &Req.Steps.compressed/1,
      put_idempotency_key: &put_idempotency_key/1,
      encode_body: &Req.Steps.encode_body/1,
      ....
    ]
  end

  defp put_idempotency_key(%Req.Request{options: %{json: json_body}} = request) do
    json_body = Map.put(json_body, :idempotency_key, Ecto.UUID.generate())
    %Req.Request{request | options: %{json: json_body}}
  end
```

Is this how we can achieve this, or am I missing something?

**Comment by wojtekmach** [comment]
Currently there is no API for this but the struct was designed in a way it could be added in the future without breaking. As you saw the step lists are keyword lists, with step names as atoms. You can write a function that would inject your step at the right place using eg List.insert_at/3.

**Comment by Arp-G** [comment]
>  You can write a function that would inject your step at the right place using eg List.insert_at/3.

Thanks this seems like a good idea, the only concern I have is if `req` decides to add a new step to that list then my `List.insert_at(2, {:put_idempotency_key, &put_idempotency_key/1})` might break

**Comment by wojtekmach** [comment]
Instead of hard coding the index to insert, dynamically find it and you should be good :) I don’t have immediate plans to add API for this so I’m going to close but will of course keep it in mind. Thank you for bringing this up.

**Comment by srowley** [comment]
Would you be interested in a PR? 

I have no need for this, so if it is not something you want to add or even spend time reviewing that is completely fine. I am just bored and seems like something to do in my spare time. 

Maybe something like the example below? The second argument could be a step or a list of steps, the third argument could take `before: step` or `after: step`. If the step doesn't exist it goes to the top (`:before`) or the bottom (`:after`) of the list (or it could throw an error I suppose).

```
iex> req = Req.Request.insert_request_steps(Req.new(),
iex>  {:inspect, &IO.inspect/1},
iex>  after: :put_user_agent)
iex> Enum.take(req.request_steps, 2)
[put_user_agent: &Req.Steps.put_user_agent/1, inspect: &IO.inspect/1]
```
