### ISSUE TITLE
[Feature Request] Allow pass-through to Finch.Request.put_private

### ISSUE THREAD

**Issue by aselder** [wojtekmach/req#152]
We're currently using `finch` and would love to move to `req`, but currently we're putting info into the Finch request using `put_private`, so that we have metadata about the request in telemetry handlers (mainly identifying targets for APM purposes).

Is there anyway to expose this in Req?

**Comment by wojtekmach** [comment]
There's no direct support at the moment. What you could do is fork the [finch adapter](https://github.com/wojtekmach/req/blob/v0.3.2/lib/req/steps.ex#L518), here's a very rudimentary one:

```elixir
defmodule MyApp.Steps do
  def run_finch(request) do
    finch_name = MyApp.Finch
    finch_options = []
    finch_private = %{}

    finch_request =
      Finch.build(request.method, request.url, request.headers, request.body)
      |> Map.replace!(:private, &Map.merge(&1, finch_private))

    case Finch.request(finch_request, finch_name, finch_options) do
      {:ok, response} ->
        response = %Req.Response{
          status: response.status,
          headers: response.headers,
          body: response.body
        }

        {request, response}

      {:error, exception} ->
        {request, exception}
    end
  end
end

Req.new(adapter: &MyApp.Steps.run_finch/1)
```

Another road we could take is extend the built-in Finch adapter with a `:finch_private` option so that we can do:

```elixir
Req.new(finch_private: %{})
```

This feature request sounds a lot like what we've been discussing in https://github.com/wojtekmach/req/issues/87 (cc @tsloughter).

Do you have a preference for API for this?

**Comment by tsloughter** [comment]
Yea, somewhat similar. Extending the built-in adapter that way of course wouldn't work for our case, but forking the finch adapter and asking people to use that if they want traces is an option.

**Comment by aselder** [comment]
Could this be as simple as adding a callback after https://github.com/wojtekmach/req/blob/3598b22830be18cf2f4e6f60e9b70d346a82086c/lib/req/steps.ex#L584.

This would allow users to do any modification they need to the finch request before execution.

```
   finch_request =
      Finch.build(request.method, request.url, request.headers, request.body)
      |> Map.replace!(:unix_socket, request.options[:unix_socket])
      |> request.options[:customize_finch].()
```

The `:customize_finch` would just default to the identity function.

**Comment by aselder** [comment]
I threw together a quick basic PR. Let me know if you approve of this approach and I'll finish fleshing out the PR. https://github.com/wojtekmach/req/pull/157

**Comment by wojtekmach** [comment]
Closing in favour of #157, thanks!
