### ISSUE TITLE
Support follow redirect without scheme?

### ISSUE THREAD

**Issue by lud** [wojtekmach/req#153]
I just ran into this problem with `Req.get!("https://www.nasa.gov/webbfirstimages")`

```
21:40:56.552 [debug] follow_redirects: redirecting to //www.nasa.gov/webbfirstimages/
** (ArgumentError) scheme is required for url: //www.nasa.gov/webbfirstimages/
```

So basically they return a redirect url that should inherit the scheme from the current page.

Should Req support that kind of redirection?

Personnally I think it should if the host does not change. In other cases, maybe passing a fun could allow to customize the behaviour.

**Comment by wojtekmach** [comment]
Yes, we should support it, a PR would be very appreciated!

**Comment by lud** [comment]
Will do

**Comment by lud** [comment]
/close

https://github.com/wojtekmach/req/pull/154
