### ISSUE TITLE
Recommended way for using an existing Finch pool as default

### ISSUE THREAD

**Issue by AdrianRibao** [wojtekmach/req#156]
I already have a Finch pool in the app, and I see I can set the name of the pool when making requests using the `:finch` option.

I want to setup the existing pool as a default, so is not necessary to set the option in each request.

I think the right way to do it is using [default_options/1](https://hexdocs.pm/req/Req.html#default_options/1), so these options are set globally.

Where do you recommend the `set_options/1` function? is `config.exs` the right place?

When we use an existing finch pool, is the `Req.Finch` pool still started? I think it does, and I don't see a way to configure the options. Is this something planned for the future?

Thanks!

**Comment by wojtekmach** [comment]
Hey!

`default_options/1` is global configuration which is pretty convenient but it is, well, global. Thus if you have a dependency that uses Req under the hood, it would use these global options too. Which may or may not be what you want.

I'd most likely use an app-specific wrapper module, e.g. `MyApp.Req`, and implement just the functions I need.

Here's another idea for a wrapper module that reimplements most of Req.* functions and passes default options. Again, I'd most likely go with the former suggestion, but here it is anyway. :)

```elixir
Mix.install([:req])

defmodule MyApp.Req do
  @defaults [
    finch: MyApp.Finch
  ]

  def new(request_or_url_or_options \\ [])

  def new(%Req.Request{} = request) do
    Req.Request.merge_options(request, @defaults)
  end

  def new(url) when is_binary(url) or is_struct(url, URI) do
    new(url: url)
  end

  def new(options) when is_list(options) do
    options |> Req.new() |> new()
  end

  for fun <-
        ~w(request request! get get! head head! post post! put put! patch patch! delete delete!)a do
    def unquote(fun)(request_or_url, options \\ []) when is_list(options) do
      request_or_url
      |> new()
      |> Req.unquote(fun)(options)
    end
  end
end

{:ok, _} = Finch.start_link(name: MyApp.Finch)

MyApp.Req.get!("https://api.github.com/repos/wojtekmach/req").body["description"]
|> dbg()

MyApp.Req.get!(MyApp.Req.new(), url: "https://api.github.com/repos/wojtekmach/req").body["description"]
|> dbg()
```

**Comment by AdrianRibao** [comment]
Hi @wojtekmach thanks a lot for all the details! I will try this right away. The way you did it is very useful for thinking about other problems in Elixir too.

Thanks!

**Comment by wojtekmach** [comment]
Another approach you might consider is something like: `MyApp.Req.new() |> Req.get(options)` or `Req.get(url, MyApp.Req.default_options())`, that is you use the `Req.*` API most of the time, just contain the common options in your own module.
