### ISSUE TITLE
Feature? `Req.from_curl(...)`

### ISSUE THREAD

**Issue by pdgonzalez872** [wojtekmach/req#159]
Hi @wojtekmach!

Have you ever considered a `Req.from_curl/1`? I think a lot of times it would be nice to copy the request a browser made and have something that could immediately translate it Req. Not sure about how this would be implemented or if this is needed at all. Just thought it was an interesting use case! To expand on it:
- `Req.from_curl/1` would return a  `Req.Request` struct
- we could then pipe that into a `Req.request`

**Comment by wojtekmach** [comment]
Great idea but I think it should start as a separate package!

**Comment by pdgonzalez872** [comment]
agree!

**Comment by pdgonzalez872** [comment]
do you have any advice/suggestion on a good approach to this problem? Or a starting point? Not sure if there is soemthing out there that does similar work.

**Comment by wojtekmach** [comment]
See https://curlconverter.com. :)

**Comment by dkuku** [comment]
> do you have any advice/suggestion on a good approach to this problem? Or a starting point? Not sure if there is soemthing out there that does similar work.

```elixir
{opts, _, _} =
  ~s|curl 'https://livebook.dev/' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-User: ?1' -H 'Sec-GPC: 1' -H 'If-None-Match: "e77c69774fcf0f1160add2a6a02206ad-ssl-df"' -H 'TE: trailers'|
  |> String.replace(" -", <<0>> <> " -")
  |> String.split(<<0>>, trim: true)
  |> Enum.flat_map(fn
    " -H " <> rest -> ["-H", String.trim(rest, "'")]
    " --compressed" -> ["--compressed"]
    "curl " <> url -> ["--url", String.trim(url, "'")]
  end)
  |> OptionParser.parse(
    aliases: [{:H, :header}],
    switches: [header: :keep, url: :string, compressed: :boolean],
    allow_nonexistent_atoms: true
  )

{url, opts} = Keyword.pop(opts, :url)
headers = Keyword.get_values(opts, :header) |> Map.new(&List.to_tuple(String.split(&1, ": ")))
Req.get(url, headers: headers)
```
