### ISSUE TITLE
Reusing a request not working after v0.3.1

### ISSUE THREAD

**Issue by forest** [wojtekmach/req#160]
We have a custom step that conditionally fans out multiple similar requests and then fans back in. We are taking the original request from the response and updating it with a few new params and then running it. This is no longer working after the addition of `current_request_steps` https://github.com/wojtekmach/req/blob/main/lib/req/request.ex#L396.

I thought that maybe the right approach is to add a way to copy a current request to get it back to a state where it can be updated and run. Something like `Req.new(request)`.

Here is the code: https://github.com/HGInsights/avalanche/blob/main/lib/avalanche/steps/get_partitions.ex#L77

Looking for your thoughts.

cc: @pdgonzalez872

**Comment by wojtekmach** [comment]
Thank you for the report. I'm still a bit fuzzy how it breaks your use case. Could you prepare a minimal example?

**Comment by wojtekmach** [comment]
Is it that when you take a request that has a certain current_request_steps and change the request slightly, change it in a way that would be picked up by a step, the change never happens because the step is no longer in current_request_steps list?

**Comment by forest** [comment]
I will try. Basically you can’t run a request twice because that steps are
removed from current.

**Comment by wojtekmach** [comment]
Right. We introduced current_request_steps to fix this bug: https://github.com/wojtekmach/req/issues/140#issuecomment-1261335856. I think you can get the previous behaviour by doing: `request = %{request | current_request_steps: request.request_steps}`. I'll think about `Req.new(request)`.

**Comment by forest** [comment]
Yes.  That is exactly what is happening. Specifically the put base url step
isn’t happening again because it is not in current.

I’ll try this out. That should fix it. Maybe a Req.reset(request) would
make sense to compliment new and update.

**Comment by forest** [comment]
Confirmed this works. Thanks.

`%{request | current_request_steps: Keyword.keys(request.request_steps)}`

**Comment by wojtekmach** [comment]
I think Req.reset/1 would be pretty natural way of going about this, but I'd first like to see a few more use cases for it before committing to adding a new function. Closing for now. Thank you!

**Comment by aleDsz** [comment]
> I think Req.reset/1 would be pretty natural way of going about this, but I'd first like to see a few more use cases for it before committing to adding a new function. Closing for now. Thank you!

It could be `Req.Request.reset_steps(request)`. WDYT?

**Comment by wojtekmach** [comment]
The problem with new/1, reset/1, reset_steps/1, etc is it is really hard to know you need this function. It will be painful to document. This current steps field probably shouldn’t even be public. In your scenario @aleDsz, we could make it so Req.post and friends always resets steps internally. But I’m not sure how to have implicit behavior for the scenario described in this ticket.
