### ISSUE TITLE
(Mint.HTTPError) Invalid request target

### ISSUE THREAD

**Issue by sergiotapia** [wojtekmach/req#161]
Hitting this URL: `https://www.bestbuy.com/site/searchpage.jsp?id=pcat17071&qp=format_facet%3DFormat~Physical&st=god+of+war+ragnarök"`

```
Req.get!(url,
  headers: [
    {"user-agent",
     "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"},
    {"accept",
     "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"},
    {"accept-language", "en-GB,en-US;q=0.9,en;q=0.8"}
  ]
)
```

Error:

> [error] retry: got exception, will retry in 1000ms, 3 attempts left
> [error] ** (Mint.HTTPError) invalid request target: "/site/searchpage.jsp?id=pcat17071&qp=format_facet%3DFormat~Physical&st=god+of+war+ragnarök"
> [error] retry: got exception, will retry in 2000ms, 2 attempts left
> [error] ** (Mint.HTTPError) invalid request target: "/site/searchpage.jsp?id=pcat17071&qp=format_facet%3DFormat~Physical&st=god+of+war+ragnarök"
> [error] retry: got exception, will retry in 4000ms, 1 attempt left
> [error] ** (Mint.HTTPError) invalid request target: "/site/searchpage.jsp?id=pcat17071&qp=format_facet%3DFormat~Physical&st=god+of+war+ragnarök"
> ** (Mint.HTTPError) invalid request target: "/site/searchpage.jsp?id=pcat17071&qp=format_facet%3DFormat~Physical&st=god+of+war+ragnarök"
>     (req 0.3.2) lib/req.ex:202: Req.get!/2
>     (app 0.1.0) lib/my_module.ex:51: MyModule.run/1

This URL format works well for other strings I have tested but I think the weird "O" in Ragnarok is causing Mint to choke?

**Comment by srowley** [comment]
That character [is not allowed unescaped in URLs]( https://www.rfc-editor.org/rfc/rfc3986#section-2).

Mint [throws an error](https://github.com/elixir-mint/mint/blob/dc655a2ebdf4c7a8556da4a0fb082b9549b54f2a/lib/mint/http1/request.ex#L59) when it's provided a URL with unescaped characters that should be escaped.

You can properly escape the URL with [URI.encode/2](https://hexdocs.pm/elixir/URI.html#encode/2).

**Comment by wojtekmach** [comment]
Thanks @srowley!
