### ISSUE TITLE
Suggestion: Have retries log at something other than `error`

### ISSUE THREAD

**Issue by aselder** [wojtekmach/req#162]
I'd love to see the `retry` step log at something other than `:error`. In many cases. retries are too be expected and aren't really an error condition.

In our case, anything that is spit out by `Logger.error` is automatically sent to our sentry instance for collection. Perhaps we should emit these log messages at `warn` or `info`; alternatively add a config option.

**Comment by wojtekmach** [comment]
Good call. How does `Req.new(retry_log_level: level)` where `level` defaults to `:warn` and can be also `false` to disable sound to you?

**Comment by aselder** [comment]
Sounds good to me. I'll get to work on a PR.

**Comment by wojtekmach** [comment]
Actually let's default it to :error for now even though I agree :warn is a better default. I'd like to ship it in Req v0.3 and change the level in v0.4 along with other breaking changes if they come up.

**Comment by aselder** [comment]
https://github.com/wojtekmach/req/pull/163
