### ISSUE TITLE
Troube sending request to IPv6 address

### ISSUE THREAD

**Issue by kokjinsam** [wojtekmach/req#166]
Hello,

I recently deployed a private app on Fly.io. Internally, Fly uses IPv6 for private apps [1]. So I explicitly enabled `inet6: true` in `connect_options` like so:

```elixir
> req = Req.new(url: "https://private-app.internal:8080/messages/new", connect_options: [transport_opts: [inet6: true]])
```

But I got the following error when trying to make the request

```elixir
> Req.post!(req)
** (Mint.TransportError) non-existing domain
    (req 0.3.5) lib/req.ex:329: Req.post!/2
```

Is there something that I'm missing?

I apologize in advance if this is not the right channel to ask this sort of question. 

Thank you.

**References**
1. https://community.fly.io/t/6pn-addressing-clarification/1362
2. https://github.com/sneako/finch/issues/163

**Comment by kokjinsam** [comment]
I found the culprit. I needed to bind to `::` instead of `0.0.0.0`

```
FROM python:3.10-slim-bullseye

ENV PYTHONUNBUFFERED True
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "::", "--port", "8080"]
```

**Comment by wojtekmach** [comment]
Thank you for the follow-up, glad everything is working well.
