### ISSUE TITLE
`run_finch`: Add `:inet6` option

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#167]
`inet6: true` will be a shorthand for setting `connect_options: [transport_opts: [inet6: true]]`.

Ref https://github.com/wojtekmach/req/issues/166, https://github.com/wojtekmach/req/issues/109

cc @sysashi @kokjinsam

**Comment by sysashi** [comment]
Just curious, what are the consequnces of setting this as default? Probably an "extra" lookup in worst case.. 🤔

**Comment by wojtekmach** [comment]
@sysashi good question. Please do research and report back!

FWIW curl first tries ipv4 and then ipv6:

```elixir
Mix.install([
  :plug_cowboy,
  :mint
])

defmodule Main do
  def main do
    children = [
      {Plug.Cowboy,
       scheme: :http,
       plug: MyPlug,
       options: [
         net: :inet6,
         ipv6_v6only: true,
         port: 4000
       ]}
    ]

    {:ok, _} = Supervisor.start_link(children, strategy: :one_for_one)

    System.cmd("curl", ~w(--no-progress-meter --fail --verbose http://localhost:4000))
    |> dbg()

    # *   Trying 127.0.0.1:4000...
    # * connect to 127.0.0.1 port 4000 failed: Connection refused
    # *   Trying [::1]:4000...
    # * Connected to localhost (::1) port 4000 (#0)
    # > GET / HTTP/1.1
    # > Host: localhost:4000
    # > User-Agent: curl/7.86.0
    # > Accept: */*
    # >~
    # * Mark bundle as not supporting multiuse
    # < HTTP/1.1 200 OK
    # < cache-control: max-age=0, private, must-revalidate
    # < content-length: 2
    # < date: Mon, 13 Feb 2023 13:24:27 GMT
    # < server: Cowboy
    # <~
    # { [2 bytes data]
    # * Connection #0 to host localhost left intact

    {:ok, conn} =
      Mint.HTTP.connect(:http, "localhost", 4000, mode: :passive, transport_opts: [])

    {:ok, conn, _request_ref} = Mint.HTTP.request(conn, "GET", "/", [], nil)
    {:ok, _conn, responses} = Mint.HTTP.recv(conn, 0, 5000)
    dbg(responses)
  end
end

defmodule MyPlug do
  def init(options), do: options

  def call(conn, _options) do
    Plug.Conn.send_resp(conn, 200, "hi")
  end
end

Main.main()
```

and I'd most likely be ok doing that in Req too.

**Comment by sysashi** [comment]
Thanks for the script, it was very helpful.
Tracing back to Mint library, it seems that if `inet6` enabled it tries to connect using ip6 first (passing `inet6` to `:gen_tcp.connect/4`) and then fallbacks to default ipv4

https://github.com/elixir-mint/mint/blob/6b932144282495b5154a4f6f0db456f96c4ec363/lib/mint/core/transport/tcp.ex#L29-L43

Regarding address resolution (in my original issue dns server also had ipv6 address) - I still have not figured it out how everything works. I tried connecting by hostname that only has ipv6 record and both ipv4 and 6, it works, but its just records in /etc/hosts. Tracing back to https://github.com/erlang/otp/blob/a108f991c0489675938eb0958f69a98d18a4460f/lib/kernel/src/inet_res.erl#L504-L505 it will try to get AAAA record back, then if there is none, mint will retry non `inet6` gen_tcp connect (which will search for A record).

All in all, I need to clarify and learn alot of things for myself to even construct a proper question - "what can go wrong" :smiling_face_with_tear: 

Also, assuming it works like I described above, setting `inet6: true` as default will always result in an extra dns lookup for AAAA record (by extra I mean if dns record only contains A record, which is most likely the case)
On the other hand, there is a cache in place (`inet_db`), which will speed things up but extra calls still will be happening.

**Comment by sysashi** [comment]
Another idea to mimic curl and much higher level is to just have an extra retry step

something like
```
defmodule Main do
  def main do
    ...
     Req.new(url: "http://localhost:4000", method: :get)
     |> Req.Request.prepend_error_steps(retry_ipv6: &retry_ipv6/1)
     |> Req.request()
    ...
  end

  def retry_ipv6({request, %{__exception__: true, reason: :econnrefused}}) do
    request = Req.Request.merge_options(request, connect_options: [transport_opts: [inet6: true]])
    {_, result} = Req.Request.run(request)
    {req, result}
  end

  def retry_ipv6({request, resp_or_exception}), do: {request, resp_or_exception}
end
```

or maybe have a special `retry` step option, similar to `:safe` but `:safe_ipv6`

@wojtekmach any guidance where I should look next? or perhaps its just better to document somewhere about tradeoffs of using an error step like that vs having `connect_options: [transport_opts: [inet6: true]]` applied on your request right away

**Comment by wojtekmach** [comment]
Sorry for radio silence. I decided to just add the inet6: true shortcut for now. Based on broader feedback we can revisit doing things automatically. Thank you!

**Comment by wojtekmach** [comment]
@sysashi hey, I just saw a related Mint issue: https://github.com/elixir-mint/mint/issues/395#issue-1636628393 and there is interest to solve this problem upstream in Mint which is the perfect outcome. If you'd like to try solving it perhaps say so in that issue to coordinate!

**Comment by sysashi** [comment]
Awesome, thanks Wojtek! I will take a look
