### ISSUE TITLE
`decompress_body`: Support transfer-encoding header

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#17]

**Comment by wojtekmach** [comment]
See https://github.com/elixir-mint/mint/blob/main/pages/Decompression.md

**Comment by andreyuhai** [comment]
I'd like to help with this one, once I get myself familiar with the text linked.

**Comment by thangpham7793** [comment]
Hello I'd like to help with this one unless @andreyuhai is still on it and thank you for the referenced doc.

Just to test the waters, would the changes be something like

1. Extract & combine the provided compression algorithms from `transfer-encoding` and `content-encoding`
2. Apply the algorithms in the given order (examples of precedence rule [here](https://github.com/tempesta-tech/tempesta-test/issues/298)).

**Comment by andreyuhai** [comment]
Sorry, I said I would but then didn't really have a chance to go beyond reading it.
Feel free to take it over @thangpham7793.

**Comment by wojtekmach** [comment]
Let's stick to content-encoding: ... for now.
