### ISSUE TITLE
Specify CA Certificate Store

### ISSUE THREAD

**Issue by tajacks** [wojtekmach/req#173]
Hello - 

I searched the existing documentation and issues, so I hope this isn't duplicated.

I have a situation where I need to contact an SSL enabled site which uses a certificate not found in common certificate stores. Does Req currently have the ability to specify a PEM encoded CA store for making requests? If possible, where can I find this documentation?

An example of this is from the Mint library itself, which allows either 

1. A CA Store dependency to be added 
2. (More flexibly) A CA Store to be specified at request time by the caller 

Reference for the above: [Mint Docs](https://github.com/elixir-mint/mint#ssl-certificates)

If this feature is not present, would it be suitable for a plugin (they seem moreso suited for post-processing) or the main library?

Thanks for the consideration

Issue to be Remediated:

```
{:error,
 %Mint.TransportError{
   reason: {:tls_alert,
    {:unknown_ca,
     'TLS client: In state wait_cert_cr at ssl_handshake.erl:2098 generated CLIENT ALERT: Fatal - Unknown CA\n'}}
 }}
```

**Comment by wojtekmach** [comment]
The documentation for HTTP connection options is here: https://hexdocs.pm/req/Req.Steps.html#run_finch/1

There is an example at the end but it is wrong, it should be:

```elixir
Req.get!(url, connect_options: [transport_opts: [cacerts: :public_key.cacerts_get()]])
```
