### ISSUE TITLE
Getting the final url after following redirects

### ISSUE THREAD

**Issue by dbernheisel** [wojtekmach/req#176]
Sometimes when crawling a site, I will get a relative path in the content. Using that relative path and attaching it to the original URL given to Req is naive and not knowledgeable about the redirects that Req followed.

Is there a way we could store the final URL after following redirects with the default follow_redirects step? I'm unsure if you want that to be available by default in the response private area.

Here's what I did in the meantime which is simple enough:

```elixir
  def track_redirected(request, opts \\ []) do
    request
    |> Req.Request.register_options([:track_redirected])
    |> Req.Request.merge_options(opts)
    |> Req.Request.prepend_response_steps(track_redirected: &track_redirected_uri/1)
  end

  defp track_redirected_uri({request, response}) do
    {request, %{response | private: Map.put(response.private, :final_uri, request.url)}}
  end
```

I'll be happy to contribute a PR if that looks harmless enough for the default follow_redirects step, but perhaps you want a more public place to store this on the response struct?

**Comment by wojtekmach** [comment]
Thanks @dbernheisel. I think this would be a nice addition. We should definitely store it in private as I'd prefer not to add new struct fields. However I'm not sure if we should store it by default or it should be opt-in. I think I'd prefer to keep response.private light/empty most of the time so that when user inspects response they got, they don't need to see a bunch of stuff they don't necessarily care about. But maybe it's fine. idk yet!

Btw

```diff
- %{response | private: Map.put(response.private, :final_uri, request.url)
+ put_in(response.private.final_url, request.url)
```

;)

**Comment by dbernheisel** [comment]
Would you rather track a stack of redirected URLs? Or just the final one? I only cared about the final one in my above example.

Sounds like I'll add another step called `:track_redirected_urls` that'll track the urls as Req follows them and add doc notes that it's only relevant when `follow_redirects: true`

**Comment by wojtekmach** [comment]
no, sorry, I think just the final url is fine. What I was trying to say was I wasn't sure whether Req should populate response.private by default.

Btw, do you really care about logging these urls? Or follow_reditects incorrectly merged them or something?

**Comment by dbernheisel** [comment]
Logging as Logger logging? I don't really care about that. Logging as in stuffing a field into response.private is fine with me so I know exactly which url gave me the response. 

For example, my specific case is visiting https://google.com, being redirected to https://www.google.com and the HTML body includes a relative path to an image, but only works on the www subdomain. I have to figure out what that final url is to construct an absolute url for the image. 

With `follow_redirects: true` and this new step `track_redirected_url: true` (is there a better name?) I can do this now by using the Req.Response private.redirected_url without making my own step app side.

The Req.Response struct doesn't have a url field that I see, but I think that might be the better option, rather than tracking in a private space. Or, as I've seen in some other libraries like httparty and python requests, attach the entire request to the response (a bit heavier).

**Comment by wojtekmach** [comment]
Got it, makes sense. Im definitely not keen on adding response.url at the moment. that aside I think what you are proposing makes sense but I’d like to wait some before setting precedent where built in steps leave stuff in response.private. I’m pretty sure we’ll end up there but in the meantime your custom step is definitely the way to go. Thanks!

**Comment by dbernheisel** [comment]
Sounds good
