### ISSUE TITLE
Question/Feature: Add option to silence follow_redirects step?!

### ISSUE THREAD

**Issue by crova** [wojtekmach/req#178]
Greetings, how is it going?

Before anything, thanks and congrats on this great library. It's by far my favorite HTTP client.

In one of the projects I work, we see ourselves logging a lot of `[debug]  follow_redirects: redirecting to https://api.github.com/` so I would like to know if you're interested in adding an option to disable them?

I have a [working fork](https://github.com/crova/req/tree/add-option-to-silence-logging-from-follow-redirect-step) with this option that we're about to use on our project, but if this was to be added here, we would prefer to stay with the original repo.

If you don't have any interest in it, please feel free to close this issue.

Cheers and again, thanks for the great work (here and elsewhere).

**Comment by wojtekmach** [comment]
Hey, thank you for the kind words.

This makes sense to me. We have as similar feature elsewhere, we can set `retry_log_level: :debug | :warn | ...` to disable logging the retries. We additionally allow setting `retry_log_level: false` to disable logging altogether for that.

A PR that adds `redirect_log_level: level | false` would be very appreciated!

**Comment by crova** [comment]
Hello, thanks for the quick feedback.

I opened https://github.com/wojtekmach/req/pull/179 that corresponds to this issue.

Cheers.

**Comment by wojtekmach** [comment]
Closing in favour if the PR.
