### ISSUE TITLE
`auth`: Support digest auth

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#19]
curl example:

```bash
$ curl --fail --user foo:bar --digest https://httpbin.org/digest-auth/auth/foo/bar
{
  "authenticated": true,
  "user": "foo"
}
```

We should support:

```elixir
Req.get!("https://httpbin.org/digest-auth/auth/foo/bar", auth: {:digest, "foo", "bar"})
```

**Comment by wojtekmach** [comment]
Re A) yup, option 1, except it would be a response step. An error step would be when we didn’t get a response but a socket error and such.

Re B) I think it is actually a good enough reason not to support it. What I mean is, if someone needs it and is willing to do the work then I’d accept a PR but otherwise it is not a high priority. I wanted to have it for completeness but you are totally right it is mostly a thing of the past.

thanks!

**Comment by zachallaun** [comment]
Sounds good! Agreed that it’s not a priority. It may be something I look to implement anyways as a small exercise. =)
