### ISSUE TITLE
Decompress doesn't support multiple `content-encoding` headers

### ISSUE THREAD

**Issue by tanguilp** [wojtekmach/req#191]
The [`content-encoding`](https://datatracker.ietf.org/doc/html/rfc9110#section-8.4) header is defined as:

```abnf
Content-Encoding = #content-coding
```

and such fields can span on [multiple lines](https://datatracker.ietf.org/doc/html/rfc9110#name-field-order), for instance:

```http
content-encoding: identity
content-encoding: gzip
```

I think [current code](https://github.com/wojtekmach/req/blob/main/lib/req/steps.ex#L1489-L1509) would fail in this case.

**Comment by wojtekmach** [comment]
Thanks for the report!
