### ISSUE TITLE
`handle_http_errors`: Support `:response` and `:exception`

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#193]
Extracted from https://github.com/wojtekmach/req/pull/188.

Example:

```elixir
Req.get("https://httpbin.org/status/400")
#=> {:ok, %Req.Response{}}

Req.get("https://httpbin.org/status/400", http_errors: :exception)
#=> {:error, %Req.Error{}}

Req.get!("https://httpbin.org/status/400", http_errors: :exception)
** (Req.Error)
```

Exact names still tbd.

**Comment by yordis** [comment]
I prefer `:return` or `:raise`/`:exception` since `@spec` uses `no_return` (notice the `return` naming) so it is a bit more familiar.

**Comment by wojtekmach** [comment]
As mentioned in https://github.com/wojtekmach/req/pull/188#issuecomment-1599356011 it is common to see things like:

```elixir
case f() do
  {:ok, resp} when resp.status in 200..299 ->
  {:ok, _} -> raise ...
  {:error, reason} -> raise ...
end
```

Maybe we also add `:expect` option to handle matching on 200..299. For example: `expect: 200`, `expect: [200, 201]`, `expect: 200..299`. Setting `:expect` (or `:expect_status` or however we'll end up calling this) will automatically raise on 4xx and 5xx responses.

**Comment by wojtekmach** [comment]
Aside from the comment above, another idea for an API is:

```elixir
http_error: :as_response (default) | :as_exception
```

**Comment by yordis** [comment]
I like both ideas but notice that you use `as_` for each value, so maybe do `http_error_as` instead.

---

In my brain that I can not let go is the `:response` thing! I wish Elixir finalize and come up with a `Result` (like Rust) naming everywhere! 😭 But whatever, maybe ChatGPT would be ideal here to move on and remove the analyzes paralysis (at least for me).

**Comment by wojtekmach** [comment]
I still can't decide on the API. I'm gonna close this but if someone finds it in the future, please feel free to continue discussing this.

It's not perfect but I think what we have today is sensible enough:

```elixir
Req.get!(req)

# if 4xx/5xx errors that would _not_ be automatically retried, do:
Req.get!(req, http_errors: :raise)

# if other 2xx/3xx might happen, do:
resp = Req.get!(req)
%{status: 200} = resp
```

**Comment by yordis** [comment]
> Im happy to remove :raise because when people use bang functions we are raising anyway.

@wojtekmach I seriously value that such a situation is just `data` over code (changing to bang function signature). I am not sure how I feel about it still 😭 😭 😭

**Comment by jeregrine** [comment]
so my issue is more with non-bang variant. All non 200 should be error'd in majority case, having option to make 200.299 -> {:ok, else {:err

**Comment by wojtekmach** [comment]
yeah I know, sorry. Just to be clear your proposal is to have `http_errors: :return | :error` ? Is it important we return an error on 3xx too?

**Comment by yordis** [comment]
> error on 3xx too

Yes, this is related to the `ok`, it is an expected behavior.
