### ISSUE TITLE
How to cancel/close a streaming response?

### ISSUE THREAD

**Issue by brainlid** [wojtekmach/req#195]
Req: 0.3.10
Finch: 0.16.0

I'm working on a ChatGPT client that streams responses. Following very closely to [this example](https://hexdocs.pm/req/Req.Steps.html#run_finch/1):

```elixir
fun = fn request, finch_request, finch_name, finch_options ->
  fun = fn
    {:status, status}, response ->
      %{response | status: status}

    {:headers, headers}, response ->
      %{response | headers: headers}

    {:data, data}, response ->
      IO.puts(data)
      response
  end

  case Finch.stream(finch_request, finch_name, Req.Response.new(), fun, finch_options) do
    {:ok, response} -> {request, response}
    {:error, exception} -> {request, exception}
  end
end

Req.get!("https://httpbin.org/stream/10", finch_request: fun)
```

How do I cancel a streaming response? I couldn't find anything in the Req or Finch docs about that. 

In my `application.ex`, there's this:
```elixir
  {Finch, name: MyApp.OpenAIFinch}
```

I've wrapped the streaming call in a GenServer that I can message and shutdown, but the streaming execution continues probably because the pool is supervised separately. 

Any advice or guidance on how to shutdown an actively streaming response?

**Comment by wojtekmach** [comment]
I don’t think there’s a way to cancel the request started by Finch.stream function. On Finch main there are new async_request and cancel_async_request functions so I’d look into using those!

**Comment by zachallaun** [comment]
It's possible to cancel the request started by `Finch.stream` by throwing/raising from within the callback function. The `async_request/cancel_async_request` should be landing in a release soon though and should be a better option!

**Comment by wojtekmach** [comment]
@brainlid fyi the plan is to [have a `Finch.stream_while`](https://github.com/sneako/finch/issues/237) where the callback function will return `{:cont, acc}` or `{:halt, acc}`, the latter cancelling the stream. And similarly we'd have something like:

```elixir
Req.new(stream: fn {:data, data}, response ->
  IO.inspect data
  {:cont, response}
end)
```

stay tuned!

**Comment by wojtekmach** [comment]
Closing in favour of #220.

**Comment by benjreinhart** [comment]
I see the new streaming support in Req and am still wondering the best way to handle this as well. I have a function that wraps the `req` call which looks like:

```elixir
def chat_completion(request_body, callback) do
  Req.post(@chat_completions_url,
    json: request_body,
    into: fn {:data, data}, {req, res} ->
      callback(data)
      {:cont, {req, res}}
    end
  )
end
```

I see that I can return `{:halt, {req, res}}` instead to cancel it. However, this seems to imply I need some state so that the function passed to the `into` option can check on each invocation if it has been cancelled and `halt` if so.

Is that right? Does this necessitate a genserver or agent with some state to make this work, or is there a simpler way?

**Comment by wojtekmach** [comment]
There's an experimental API that uses process messages. It's available but undocumented at the moment. I'm pretty sure it will stay as is but there could be some changes before Req v1.0.

```elixir
iex> Mix.install([:req])
iex> Req.async_request!("https://reqbin.org/ndjson")
iex> flush
{{Finch.HTTP1.Pool, #PID<0.243.0>}, {:data, "{\"y\":1,\"x\":1}\n"}}
{{Finch.HTTP1.Pool, #PID<0.243.0>}, {:data, "{\"y\":2,\"x\":2}\n"}}
{{Finch.HTTP1.Pool, #PID<0.243.0>}, {:data, "{\"y\":3,\"x\":3}\n"}}
{{Finch.HTTP1.Pool, #PID<0.243.0>}, :done}
```

```elixir
iex> {req, resp} = Req.async_request!("https://reqbin.org/ndjson?delay=5000")
iex> Req.cancel_async_request(req)
iex> flush
{{Finch.HTTP1.Pool, #PID<0.243.0>}, {:data, "{\"y\":1,\"x\":1}\n"}}
```

**Comment by benjreinhart** [comment]
That looks very helpful for removing glue code to make all this work otherwise, thank you!

**Comment by wojtekmach** [comment]
Yup

**Comment by wojtekmach** [comment]
Hey just a quick heads up, I ended up with a very similar but ultimately different API after all:

```elixir
iex(1)> Mix.install([{:req, github: "wojtekmach/req"}])
:ok
iex(2)> resp = Req.get!("https://reqbin.org/ndjson", into: self())
#Req.Response<
  status: 200,
  headers: %{
    "cache-control" => ["max-age=0, private, must-revalidate"],
    "content-type" => ["application/x-ndjson; charset=utf-8"],
    "date" => ["Mon, 04 Mar 2024 15:20:25 GMT"],
    "fly-request-id" => ["01HR50THAK6SNNWZQX32BV1GYY-waw"],
    "server" => ["Fly/17ce28b7 (2024-03-02)"],
    "via" => ["2 fly.io"]
  },
  body: "",
  trailers: %{},
  private: %{},
  ...
>
iex(3)> Req.parse_message(resp, receive do message -> message end)
{:ok, [data: "{\"y\":1,\"x\":1}\n"]}
iex(4)> Req.parse_message(resp, receive do message -> message end)
{:ok, [data: "{\"y\":2,\"x\":2}\n"]}
iex(5)> Req.cancel_async_response(resp)
:ok
```

This is now on main and will be part of next release which should be out this week.
