### ISSUE TITLE
`Req.new`: Validate header keys are lower case

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#196]
Similar to:

> By default, Plug tests checks for invalid header keys, e.g. header keys which include uppercase > letters, and raises a [Plug.Conn.InvalidHeaderError](https://hexdocs.pm/plug/Plug.Conn.InvalidHeaderError.html) when it finds one. To disable it, set > :validate_header_keys_during_test to false on the app config.

(https://hexdocs.pm/plug/Plug.Test.html)

**Comment by octowombat** [comment]
Is this still open to. work on? If so I will have a look and come back with any questions here.

**Comment by wojtekmach** [comment]
Yes it is!

**Comment by dokie** [comment]
Were you thinking that;
- Headers passed that are not already normalised to lower case should raise an error?
- Can this be overridden by passing a suitably named boolean option e.g. `:force_normalised_headers`?

**Comment by octowombat** [comment]
Were you thinking that;

1. Headers passed that are not normalised already to lowercase should raise an error?
2. This validation _could_ be overridden by passing a suitably named boolean option, such as `;headers_are_normalised`, or
3. The default is not to enforce this for backward compatibility but to use the option above to enforce?

**Comment by wojtekmach** [comment]
Yes I think so. Do you have a preference how this should work?

I was thinking something lukę this: `invalid_header_keys: :warn (default) | :raise | :ignore`.

**Comment by dokie** [comment]
That is how I would imagine using it yes.

**Comment by octowombat** [comment]
Yes, that's how I would imagine using it, whether I was newly using `req` or had an existing codebase using it.

**Comment by wojtekmach** [comment]
Closing in favour of #211
