### ISSUE TITLE
`run_finch`: Add docs on Finch pools

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#198]
Finch starts pool for each {protocol, host, port}, so we might end up with a bunch of pools after a while. We should document this, mention :pool_max_idle_time option, and make it possible to pass that option down to Finch.

**Comment by acco** [comment]
@wojtekmach Was just looking for Req + Finch pools docs :) Is there a way to configure the Finch pools that Req uses globally? e.g. how Finch does it:

```
children = [
  {Finch,
   name: MyConfiguredFinch,
   pools: %{
     :default => [size: 10],
     "https://hex.pm" => [size: 32, count: 8]
   }}
]
```

**Comment by wojtekmach** [comment]
Yes, `Req.new(finch: MyConfiguredFinch)`. See `Req.Steps.run_finch/1` for more information.

**Comment by acco** [comment]
@wojtekmach Just to confirm: That's for an individual Req.Request instance, right? I'm wondering about a way to change the default `finch` adapter/setting for all Req.Request structs.

**Comment by wojtekmach** [comment]
You can use Req.default_options/1 for that but it is better to avoid this global configuration and instead pass the options explicitly to Req.new, Req.get etc.
