### ISSUE TITLE
Frequently getting Mint.TransportError

### ISSUE THREAD

**Issue by DaTrader** [wojtekmach/req#201]
What may be the reason of frequently getting a Mint.TransportError?

Even when I try to run the sample code from the docs (https://hexdocs.pm/req/Req.Steps.html#retry/1), I also get this error as shown below. 

```elixir
iex(4)> Req.get!("https://httpbin.org/status/500,200").status
[error] retry: got exception, will retry in 1000ms, 3 attempts left
[error] ** (Mint.TransportError) timeout
200
```

Is this a bug or a configuration error?

**Comment by wojtekmach** [comment]
httpbin.org is slow lately. I plan to update docs with some other service at some point.
