### ISSUE TITLE
Content Range - put_range step has wrong implementation

### ISSUE THREAD

**Issue by TwistingTwists** [wojtekmach/req#205]
https://github.com/wojtekmach/req/blob/v0.3.11/lib/req/steps.ex#L416

the docs say that `put_range/1` sets the `"content-range"` header. It actually, sets the `"range"` header as seen from code above. 

Either the docs need to change or the `put_range/1`. 

Willing to raise a PR.

**Comment by TwistingTwists** [comment]
https://github.com/wojtekmach/req/blob/v0.3.11/lib/req/steps.ex#L420

Additionally, `bytes=0-3/100` is not the syntax followed in `content-range` header. 
it is `bytes 0-3/100` (notice, no `=`)
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range#examples

**Comment by wojtekmach** [comment]
Good find. The client sets "range" and the server responds with "content-range". Please send a PR!

**Comment by wojtekmach** [comment]
Sorry, I only now was able to see this on the computer. Both the code and the docs are correct. The docs say we set "range" header. You saw "content-range" in the docs but that was from the response.

**Comment by TwistingTwists** [comment]
Oh. that part skipped from my eyes as well!

On a different note, I wrote a custom Req.Step where I set `content-range` in request, instead of `range`. That worked! So I assumed that we need to set `content-range` here too. 

Maybe both `range` and `content-range` in request work.

**Comment by wojtekmach** [comment]
Yes you can set any header and servers most likely ignore the ones they don’t know about.
