### ISSUE TITLE
Set up a step at a specific place

### ISSUE THREAD

**Issue by tanguilp** [wojtekmach/req#229]
Hello!

I have the following problem configuring `http_cache` as a step. Currently the step is appended in this way (shortened for clarity):
```elixir
iex(9)> Req.new(url: "https://api.github.com/repos/wojtekmach/req") |> ReqHTTPCache.attach(%{store: :http_cache_store_process})              
%Req.Request{
  method: :get,
  url: URI.parse("https://api.github.com/repos/wojtekmach/req"),
  headers: %{},
  body: nil,
  options: %{...
    }
  },
  registered_options: MapSet.new(...),
  halted: false,
  adapter: &Req.Steps.run_finch/1,
  request_steps: [
    put_user_agent: &Req.Steps.put_user_agent/1,
    compressed: &Req.Steps.compressed/1,
    encode_body: &Req.Steps.encode_body/1,
    put_base_url: &Req.Steps.put_base_url/1,
    auth: &Req.Steps.auth/1,
    put_params: &Req.Steps.put_params/1,
    put_path_params: &Req.Steps.put_path_params/1,
    put_range: &Req.Steps.put_range/1,
    cache: &Req.Steps.cache/1,
    put_plug: &Req.Steps.put_plug/1,
    compress_body: &Req.Steps.compress_body/1,
    read_from_http_cache: #Function<1.19761999/1 in ReqHTTPCache."-fun.read_from_http_cache/1-">
  ],
  response_steps: [
    retry: &Req.Steps.retry/1,
    follow_redirects: &Req.Steps.follow_redirects/1,
    decompress_body: &Req.Steps.decompress_body/1,
    decode_body: &Req.Steps.decode_body/1,
    handle_http_errors: &Req.Steps.handle_http_errors/1,
    output: &Req.Steps.output/1,
    cache_response: #Function<2.19761999/1 in ReqHTTPCache."-fun.cache_response/1-">
  ],
  error_steps: [
    retry: &Req.Steps.retry/1,
    get_stale_from_cache: #Function<3.19761999/1 in ReqHTTPCache."-fun.get_stale_from_cache/1-">
  ],
  private: %{}
}
```

There are 2 problems with this approach:
- caching response in the `cache_response` step requires an IOdata, but the `decode_body` transforms the body into a map
- `cache_response` returns a gziped version of the payload, because the `request` object has an `accept-encoding: gzip` header

I could append the `cache_response` instead, but I think it'd be better to have it between `follow_redirects` and before `decompress_body`. I think it's not possible with the current API, and even if it would, it would be a nightmare to configure for the users.

What do you think is the best approach to tackle this problem?

**Comment by wojtekmach** [comment]
I was thinking about something like this:

```elixir
|> Req.add_request_steps([bar: &bar/1], after: :foo)
|> Req.add_request_steps([bar: &bar/1], before: :foo)
```

but haven't decided on the exact API yet. If you have any feedback, please drop a comment in #170. :)

**Comment by wojtekmach** [comment]
I haven't had time to thoroughly check your `http_cache` and `plug_http_cache` work but I'm very keen on an integration with Req. Thank you for looking into it.

For now we have the very simplistic [`cache`](https://hexdocs.pm/req/Req.Steps.html#cache/1) step. If it could be in the way of enabling more comprehensive cache solution please let me know, I can deprecate it v0.4 which will be out next week.

One nice advantage of a built-in cache step is we can put it in an exact place. So another idea is something like this:

```elixir
# built-in:
cache: :naive

# uses req_http_cache package
cache: ReqHTTPCache
```

**Comment by tanguilp** [comment]
> but haven't decided on the exact API yet. If you have any feedback, please drop a comment in #170. :)

Looks like this issue is a duplicate, and should be closed. Thanks for the link :) Not feedback yet but I'll give it a thought.



> I haven't had time to thoroughly check your `http_cache` and `plug_http_cache` work but I'm very keen on an integration with Req. Thank you for those packages and even looking into how they could work with Req.

There's a Tesla middleware actually: https://github.com/tanguilp/tesla_http_cache

WIP for Req step: https://github.com/tanguilp/req_http_cache (code is very similar).

> For now we have the very simplistic [cache](https://hexdocs.pm/req/Req.Steps.html#cache/1) step. If it could be in the way of enabling more comprehensive cache solution please let me know, I can deprecate it v0.4 which will be out next week.

I think it's too early. Depends on whether you consider there should be a minimal version included or not. By the way I couldn't have it working by simply using `cache: true`:

```elixir
Req.new(url: "https://perdu.com", cache: true, cache_dir: "/tmp/")
```

Is it required to attach it manually?

> One nice advantage of a built-in cache step is we can put it in an exact place. So another idea is something like this:

That's a neat idea. The question is: would every cache need to be placed at the same step?

The JSON example is a good one: I took the decision to disallow caching non-iodata in `http_cache` for performance reason (binary is just a pointer) and others. This is why `ReqHTTPCache` step must be before body decoding. But I or another library user could have done otherwise, as [ETS](https://github.com/tanguilp/http_cache_store_memory) support any Erlang term. Therefore a cache could want to be placed after body decoding, trading memory consumption for performance (no need to decode JSON every time).

**Comment by wojtekmach** [comment]
> This is why ReqHTTPCache step must be before body decoding. But I or another library user could have done otherwise, as [ETS](https://github.com/tanguilp/http_cache_store_memory) support any Erlang term.

Yeah I could see some arguments for caching Elixir terms but I think it would be way more reliable to cache the raw response because it is more versatile, it can be restored into any set of steps, not just the particular one that were used to cache it.

For that reason `cache: mod` is pretty appealing to me, to make _some_ choices but leave the details to implementors. But yeah need more research and prototypes.

Anyhow I'm going to close this in favour of #170.
