### ISSUE TITLE
HEAD requests seem to become GET requests, fetching the whole body when there's a 302 redirect

### ISSUE THREAD

**Issue by doawoo** [wojtekmach/req#235]
Similar to #175

Wanted to comment here and say I'm seeing this behavior with a standard `302` redirect when trying to run a `HEAD` request against a GitHub CDN file.

Can be reproduced with: 

```
Req.head("https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/clang+llvm-15.0.6-x86_64-linux-gnu-ubuntu-18.04.tar.xz")
```

Req will follow the redirect, then try to download the whole body/archive

**Comment by wojtekmach** [comment]
That's embarrassing, thank you so much for reporting this!
