### ISSUE TITLE
`decompress_body`: Do we want to recalculate `content-length`?

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#239]
Both `fetch()` and `reqwest` are dropping them: https://github.com/wojtekmach/req/pull/190#issuecomment-1683590493

**Comment by wojtekmach** [comment]
Same for Go `net/http`:

```go
package main

import (
  "fmt"
  "net/http"
)

func main() {
    resp, _ := http.Get("https://httpbin.org/gzip")
    fmt.Printf("resp.Uncompressed = %v\n", resp.Uncompressed)
    for name, values := range resp.Header {
        fmt.Printf("%v: %v\n", name, values)
    }
}
```

```
resp.Uncompressed = true
Date: [Sun, 03 Sep 2023 11:47:30 GMT]
Content-Type: [application/json]
Server: [gunicorn/19.9.0]
Access-Control-Allow-Origin: [*]
Access-Control-Allow-Credentials: [true]
```

**Comment by yordis** [comment]
🤔 when would such value become valuable to recompute vs. letting upstream recompute it?

The only use cases I am thinking off is proxies-like use cases, but I am not sure if somebody should rely on the headers or be safe and check the body 🤷🏻 

Any commitment to a particular behavior from your end thus far?

**Comment by wojtekmach** [comment]
Yeah exactly not sure we need to recompute it so I wouldn’t but ideally there is some prior art to go one way or the other.

**Comment by yordis** [comment]
Would it be a good bet to follow `fetch` from the browser? I know it is silly, but the less computation the better.

While typing something came to my mind: how OTEL**** and telemetry would handle the situation?
