### ISSUE TITLE
:redact_auth option is missing from registered option

### ISSUE THREAD

**Issue by igortalsky** [wojtekmach/req#242]
* in test.exs set config :req, :default_options, redact_auth: false
* run MIX_ENV=test mix test (assuming you have a test using req)

Error: ** (ArgumentError) unknown option :redact_auth

**Comment by igortalsky** [comment]
I have a fix for this by basically adding :redact_auth to the registered options list, but I was not able to create a branch due to permissions.

**Comment by wojtekmach** [comment]
Fixed in cdf7735112e6f95365b74d1c5db8c4adeba895fa.

**Comment by wojtekmach** [comment]
Thank you for the report! Did you try pushing your branch to this repo? Should have pushed to your fork. :)
