### ISSUE TITLE
[Breaking Change] Change Path Params step token

### ISSUE THREAD

**Issue by yordis** [wojtekmach/req#243]
Before comitting to v1, I strongly suggest to move away from `:token_name` to `{token_name}`

Related to https://github.com/elixir-tesla/tesla/issues/566#issuecomment-1643441483; read the entire thread for more context.

**Comment by wojtekmach** [comment]
Thank you. We have the same bug:

```elixir
iex> Req.new(url: "http://example.com/:foo/:bar", path_params: [foo: 1]) |> Req.Request.prepare() |> Map.fetch!(:url) |> URI.to_string()
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

    :erlang.binary_to_existing_atom("bar", :utf8)
```

however if the atom happens to already exist:

```elixir
iex> :bar
iex> Req.new(url: "http://example.com/:foo/:bar", path_params: [foo: 1]) |> Req.Request.prepare() |> Map.fetch!(:url) |> URI.to_string()
"http://example.com/1/:bar"
```

and we were shooting for these semantics, if the path param does not exist, leave the url as is. Even if we switch to `{param}` not sure if we should change semantics.

In other words I think these are orthogonal problems. I think we shouldn't crash. And whether we should go with `{param}` is a separate discussion.

Maybe `{param}` could have been a better starting point but not sure. Kinda reminds me of Phoenix verified routes: `~p"/#{foo}"`. However, what we have today looks similar to Plug.Router `get "/:foo"` too.

I noticed some differences between `:param` and `{param}`:

```elixir
iex> URI.encode "/foo/:bar"
"/foo/:bar"
iex> URI.encode "/foo/{bar}"
"/foo/%7Bbar%7D"
```

Also:

```elixir
iex> URI.parse("/foo/{bar}")
%URI{
  scheme: nil,
  userinfo: nil,
  host: nil,
  port: nil,
  path: "/foo/{bar}",
  query: nil,
  fragment: nil
}

iex> URI.new("/foo/{bar}")
{:error, "{"}
```

So `{param}` might be a more solid choice after all, it is not supposed to show up verbatim in URLs. But then if we don't have a `:path_params` value corresponding to a {param}, we raise?

wdyt about all this @bryannaegele?

**Comment by yordis** [comment]
> Whether we should go with {param} is a separate discussion.

Right, I am trying to align with you because I strongly, after so many years, that every implementation out there should use it. OpenAPI is so familiar and established that I am biased by now.

Do you think we could align here? I know it is two packages, but I care about the ecosystem above everything. 

> But then if we don't have a :path_params value corresponding to a {param}, we raise?

In OpenAPI Spec, you define whether a given parameter is required. https://github.com/beam-community/stripity-stripe/blob/f672c114c2ece522d31a8ccddb182805d535c508/lib/generated/account.ex#L665

So, 🤷🏻 it really depends! Sometimes, it could be optional!

For both `Req` and `Tesla,` I am leaning towards having a configuration for them:


```elixir
Req.get!(
  "https://httpbin.org/status/:code",
  path_params: {[code: 200], [code: true]},
)
```

**Comment by bryannaegele** [comment]
I'll think about the raise part but just on the formatting part for the purpose of discussion in case this changes anything in your thoughts @wojtekmach:

I'm trying to keep it consistent with the server route conventions we have generally in Elixir (Phoenix in particular) of the colon token. The semantic conventions state [the route should match the server framework's convention](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions) and I don't want to have to do string manipulation for the given route.

> Given an inbound request for a route (e.g. `"/users/:userID?"`) the name attribute of the span SHOULD be set to this route.

I agree on the orthogonal problems part. The path params bit we put into Req core, so I think that bit becomes a question for there with obvious impacts here. I just don't think it's realistic for any of the libs to try to settle on conventions that are different than the most dominant convention in Phoenix and that all other frameworks are currently using that convention, as well.

**Comment by wojtekmach** [comment]
Thanks all. I'll address other points soon.

RE raising, I think it's fairly reasonable to raise on `{param}` given we're supposed to escape `{` and `}` if that makes sense. It's totally fine to use `:` in an URL so it is trickier to decide whether we should raise and I think we probably shouldn't

One nice thing about raising is we can catch typos.

**Comment by yordis** [comment]
Good point! It made me rethink whatever I felt was the final solution. I am waiting for your commitment to fix Tesla.

**Comment by wojtekmach** [comment]
> Do you think we could align here? I know it is two packages, but I care about the ecosystem above everything.

Yeah I think it'd be nice to be consistent. There's plenty of time to decide, if we were to change to `{param}`, which I'm not saying we will, there's no rush for Req v1.0 and I'd imagine even less so for Tesla v2.

**Comment by wojtekmach** [comment]
>  I just don't think it's realistic for any of the libs to try to settle on conventions that are different than the most dominant convention in Phoenix and that all other frameworks are currently using that convention, as well.

@bryannaegele yeah this is a very good point. I think the {param} thing has some nice things going for it as I mentioned earlier but feels like it's way more practical to just leave things as is both in terms of what people would be more familiar with (given plug/phoenix) and not go through breaking change.

**Comment by bryannaegele** [comment]
Yeah, I don't have a strong opinion on what the tokens are. They're at least consistent right now. 😆

**Comment by yordis** [comment]
@wojtekmach what are you thinking thus far?

**Comment by wojtekmach** [comment]
At the moment I plan to keep things as is, `:param`, but I'm keeping an open mind. I'm planning to make a decision in a couple weeks. No rush in any case.

**Comment by halostatue** [comment]
One suggestion would be to keep `:param`, but if there is a colon in the path (since it's legal), either it needs to be doubled up (`:param::requestLoader` would be the same as OpenAPI `{param}:requestLoader`) or `\` escape it (`:param\:requestLoader` would be the equivalent of `{param}:requestLoader`). RFC 3986 does not include `\` in characters that do not need URL encoding.

**Comment by wojtekmach** [comment]
We're gonna keep things as is, the `:param` notation for Req v1. If folks run into any issues down the road we can revisit this. Thanks everyone for feedback!

**Comment by yordis** [comment]
I found that the new Go built-in web server will use `{name}` as well.

**Comment by bryannaegele** [comment]
> I found that the new Go built-in web server will use `{name}` as well.

The difference there though is Go has a singluar HTTP package/struct (whatever the call it) that is used for _everything_, so they can change things across the entire ecosystem. They have a luxury where they essentially have `Plug.Conn` everywhere.

**Comment by wojtekmach** [comment]
FYI: In #373 we added a `path_params_style: :colon (default) | :curly)` option. In other words, this now works:

```elixir
iex> Mix.install([{:req, github: "wojtekmach/req"}])
iex> Req.get!("https://httpbin.org/status/{code}", path_params: [code: 201], path_params_style: :curly).status
201
```
