### ISSUE TITLE
Consider using URI.new!

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#245]
If users need something more relaxed they can call URI.parse on the string themselves.

**Comment by yordis** [comment]
Where would this be? Are you saying that you would pass the `URI` struct instead of a string as the URL around?

**Comment by wojtekmach** [comment]
The :url option to Req.new, Req.update, etc, allows a %URI{} and a string and we covert the latter to the former using URI.parse. the idea is to use something more strict.

**Comment by yordis** [comment]
How would you handle the situation where middleware may add the remaining URL parts, but the first section isn't a complete "valid" URL?

**Comment by wojtekmach** [comment]
if you mean something like `Req.new(base_url: "https://api.github.com", url: "/user")`, the way it works is :url is converted to %URI{} but :base_url stays as a string.

**Comment by wojtekmach** [comment]
Note to self: if we were to change this, we need to change both Req and Req.Request modules.

**Comment by wojtekmach** [comment]
Let's stick to URI.parse especially since users expect things like:

```elixir
iex> Req.get!("https://httpbin.org/anything?foo[x]=1").body["args"]
%{"foo[x]" => "1"}
```

to just work.
