### ISSUE TITLE
Testing guide

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#246]

**Comment by wojtekmach** [comment]
Yup, much appreciated. I plan to discuss :plug and :adapter and when to decide between the two. And when to reach for Max or similar solutions. Thanks!

**Comment by yordis** [comment]
Ideally, `plug` so the technicality of the adapter doesn't matter (user space).

You are mocking the "network" stack. Similar to https://www.npmjs.com/package/msw 

So definitely would recommend to create testing support around `plug`

**Comment by thbar** [comment]
Is it a testing guide "for the user of Req", presumably?  If this is the case, I've been actually looking for this, here is my feedback based on what I experienced.

On a codebase using `HTTPoison`, a large number of tests were relying on the fact that `HTTPoison` introduces a behaviour and this allowed us to use Mox (which we pretty much use everywhere now).

I was assuming a behaviour would be there, but did not find information, and ultimately stumbled upon:
- https://github.com/wojtekmach/req/issues/143

Which explain the stance (which seems reasonable!).

I would probably at least mention that in the README, and maybe provide some basic example implementation.

E.g.

```elixir
defmodule MyApp.Req.Behaviour do
  # Req apparently does not define a Behaviour that we can Mox directly, recommending
  # instead to mock "above" (via some wrapper) or "below" (via bypass)
  # See https://github.com/wojtekmach/req/issues/143
  # Ref: https://github.com/wojtekmach/req/blob/b40de7b7a0e7cc97a2c398ffcc42aa14962f3963/lib/req.ex#L545
  @type url() :: URI.t() | String.t()
  # Simplified version for our needs
  @callback get(url(), options :: keyword()) :: {:ok, Req.Response.t()} | {:error, Exception.t()}
end

defmodule MyApp do
  def impl, do: Application.get_env(:transport, :req_impl, __MODULE__)

  @behaviour Transport.Req.Behaviour
  defdelegate get(url, options), to: Req
end
```

Then later in a `mocks.ex`:

```elixir
Mox.defmock(MyApp.Req.Mock, for: MyApp.Req.Behaviour)
```

And in `test.exs`:

```elixir
config :my_app,
  req_impl: MyApp.Req.Mock,
```

And maybe an couple of examples during tests!

An example of testing with streaming enabled I came up with:

```elixir
  def setup_req_mock(resource_url, csv_content, opts \\ []) do
    opts = Keyword.validate!(opts, status: 200)

    MyApp.Req.Mock
    |> expect(:get, fn ^resource_url, options ->
      assert options[:compressed] == false
      assert options[:decode_body] == false
      stream = options |> Keyword.fetch!(:into)
      # fake write
      File.write!(stream.path, csv_content)

      {:ok,
       %Req.Response{status: opts[:status], headers: [{"Content-Type", "application/octet-stream"}, {"x-foo", "bar"}]}}
    end)
  end
```

Happy to contribute in a way or another.

**Comment by wojtekmach** [comment]
Thanks @thbar! I plan to take a stab at this in the next week or so. Can I ping you with a draft for some feedback?

As I alluded to previously I intend to focus on :plug and possibly :adapter features. I hoped  these are enough to not have to add a mock for Req itself. And if adding mocks for anything, it would be for "above" Req. But I try to keep an open mind. :)

**Comment by thbar** [comment]
> Can I ping you with a draft for some feedback?

Sure, also please note I'm a bit overloaded at the moment so my response time will likely be a bit high :smile:

> As I alluded to previously I intend to focus on :plug and possibly :adapter features.

I have not dived into that but initially I did not understand what this was about (as a newcomer on that area).

> And if adding mocks for anything, it would be for "above" Req.

Having done that after reading the issues, I feel it's an acceptable stance and just explaining it & giving examples would be good enough (I've implemented mocks above Req last week & things worked out fine).

**Comment by woylie** [comment]
I just set up a mock for Req using Hammox.

I like to keep the mock surface as small as possible. I usually put some validation at the edge and transform responses into data structures that are easier to use within the application. I don't like to mock the whole module then, since these validation and transformation steps wouldn't be called in the tests. On the other hand, Bypass on its own does not solve the problem of passing the Bypass URL to the request function, requiring some manual test setup when it comes to tests for controllers and live views that make a request at some point. So this is what I did instead.

Define a `ReqAdapter` behaviour, along with an implementation of that behaviour that uses the default adapter:

```elixir
defmodule MyApp.ReqAdapter do
  @moduledoc """
  Defines a behaviour for a Req adapter to allow mocking requests with Mox or Hammox.
  """
  @callback run(Req.Request.t()) ::
              {Req.Request.t(), Req.Response.t() | Exception.t()}

  defmodule Finch do
    @moduledoc """
    Default implementation of `MyApp.ReqAdapter` that uses the default adapter
    of Req.
    """
    @behaviour MyApp.ReqAdapter

    @impl MyApp.ReqAdapter
    def run(%Req.Request{} = request), do: Req.Steps.run_finch(request)
  end
end
```

In the API client module, get the adapter to use from the Application environment:

```elixir
defmodule MyApp.SomeService do
  def fetch_items do
    Req.get(request(), url: "/items")
  end

  defp request do
    Req.new(base_url: "https://this.service.does.not.exist"), adapter: &req_adapter().run/1)
  end

  defp req_adapter do
    :my_app
    |> Application.get_env(__MODULE__, [])
    |> Keyword.get(:req_adapter, MyApp.ReqAdapter.Finch)
  end
end
```

Configure a Hammox (or Mox) mock in `test/test_helper.exs`:

```elixir
Hammox.defmock(MyApp.ReqAdapter.Mock, for: MyApp.ReqAdapter)
```

In `config/test.exs`, configure the mock implementation for the service module:

```elixir
config :my_app, MyApp.SomeService, req_adapter: MyApp.ReqAdapter.Mock
```

Add `test/support/mock.ex` with a helper for building JSON responses:

```elixir
defmodule MyApp.Mock do
  @moduledoc """
  Defines test helpers for defining mocks.
  """

  @doc """
  Takes a response body, encodes it as JSON, and returns a `Req.Response`.

  ## Usage

        import Hammox
        import MyApp.Mock

        expect(MyApp.ReqAdapter.Mock, :run, fn
          %Req.Request{} = request ->
            {request, json(%{msg: "hello"})}
        end)

  You can also set the status and add headers:

      json(%{msg: "hello"}, status: 201, headers: %{"x-example" => "again"})}
  """
  def json(body, opts \\ []) do
    opts = Keyword.validate!(opts, headers: [], status: 200)

    put_headers(
      %Req.Response{
        status: opts[:status],
        body: Jason.encode!(body),
        headers: %{"content-type" => ["application/json"]},
        # Added because `Req.Response.t` requires at least one trailer to be
        # present. Hammox would complain about breaking the contract
        # without this.
        trailers: %{"X-Dummy-Trailer" => ["none"]}
      },
      opts[:headers]
    )
  end

  defp put_headers(%Req.Response{} = response, headers) do
    Enum.reduce(headers, response, fn {key, value}, acc_response ->
      Req.Response.put_header(acc_response, key, value)
    end)
  end
end
```

With this setup, `MyApp.ReqAdapter.Mock` can be reused in any service modules that require mocking. You also retain control over which requests to mock in the first place.

If you think any of this is useful for Req (code or documentation), let me know. I'd be happy to open a PR.

**Comment by wojtekmach** [comment]
Thanks @woylie, I'll take this into consideration when working on the testing guide.

> Added because `Req.Response.t` requires at least one trailer to be present.
> `trailers: %{"X-Dummy-Trailer" => ["none"]}`

I fixed the type on main, we definitely don't require any headers or trailers to be present.

**Comment by codeadict** [comment]
A good testing guide to follow as an example is https://github.com/seancribbs/hardhat#testing

**Comment by yordis** [comment]
My :2cents: anything closer to `Bypass` (swapping the plug), with the most declarative way to compose the plug will be the way to go to avoid leading to inconsistencies, especially around Marshalling and putting headers and whatnot.

I remember working on https://github.com/stueccles/okta-elixir/blob/master/test/support/helpers.ex and it feels quite pleasant to use: https://github.com/stueccles/okta-elixir/blob/f7831125e40a1b4f8b488528b6a09b87d654db45/test/groups/groups_test.exs#L33-L38

But I would try to achieve the same without `Mox`, a way to compose a plug in my test case that acts as an Assertion of the Command (Http Request), and Mocking of the Response (Http Response).

**Comment by wojtekmach** [comment]
Thank you everyone for chiming in. I have created a proposal: https://github.com/wojtekmach/req/issues/287. Any feedback welcome!

**Comment by wojtekmach** [comment]
The Req.Test module is a good enough for now, I might add a dedicated testing guide in the future.
