### ISSUE TITLE
Getting information about the request struct

### ISSUE THREAD

**Issue by petejodo** [wojtekmach/req#248]
Req is super useful so just wanted to explain an issue I ran into for a potential DX improvement, whether that's documentation or actual changes.

Trying to interact with some API (Auth0's to be exact) and I make use of `Req.new` with a `base_url` set. Then when making the actual API call, it's a `Req.post!(req, url: "/path/to/endpoint")`. I'm getting back a 404 but it's not immediately clear why from looking at my code. I'm trying to now figure out what the actual final URL was to see if I can spot something but I can't seem an easy way to get that information. I put a `dbg(response)` but that doesn't have the url and there's nothing in the documentation that explicitly mentions how to do this even though I know for sure `Req` is capable of it somehow.

My suggestion is at the very least some debugging tips in the documentation e.g. here's how to view the request struct when the request is actually made or something along those lines.

I apologize if that's there and I just missed it but I'm pretty sure I took a thorough look through the top level documentation. Note I didn't dig too deep into the low-level APIs but I did that almost purposely because I feel like doing something like this shouldn't be hidden in the low-level documentation. Thanks!

**Comment by wojtekmach** [comment]
Thank you for the report.

we have an example of creating a request step that inspects the URL here: https://github.com/wojtekmach/req#usage

this is less obvious but you can call https://hexdocs.pm/req/Req.Request.html#run_request/1 and get back {req, resp} and inspect them.

If you could update docs with where you’d expect this information to be I’d really appreciate it.

finally, I’m planning to add a step that would dump the raw request and response, similar to `curl -i`.

**Comment by petejodo** [comment]
Dang it, that's exactly what I'm looking for. I just missed it. I'm going to reread hexdocs to see maybe how I missed it and will see if I actually have a suggestion otherwise I'll close this ticket. Thanks

**Comment by wojtekmach** [comment]
as mentioned earlier we're considering adding a logging step #249.
