### ISSUE TITLE
Finch: Add option for storing private options onto Finch request (for telemetry)

### ISSUE THREAD

**Issue by dbernheisel** [wojtekmach/req#251]
I'm looking to add some private data to Finch requests so I can catch them in [telemetry events](https://hexdocs.pm/finch/Finch.Telemetry.html).

Currently, the finch options are limited to `[:receive_timeout, :pool_timeout]` and it looks like I'd need to rebuild much of Req's finch adapter (especially re: streaming) to be able to inject private options onto the `%Finch.Request{}` via the `:finch_request` option myself. 

For non-streaming requests, it looks simple enough to add a `:finch_request` option and not miss much of Req's features:

https://github.com/wojtekmach/req/blob/59db3e26e3baab3b1af95c27bcc5045e5b3b0aff/lib/req/steps.ex#L699-L701

https://github.com/wojtekmach/req/blob/59db3e26e3baab3b1af95c27bcc5045e5b3b0aff/lib/req/steps.ex#L834-L839

This is reasonable for me bring into the app for normal requests, for example:

```elixir
# My Req shim provides setup with default options, and this would be one of them:
defp put_finch_request(opts) do
  finch_private = Keyword.get(opts, :finch_private, %{})

  Keyword.put_new(:finch_request, fn _req, finch_req, finch_name, finch_options ->
    finch_req = Enum.reduce(finch_private, finch_req, fn {k, v}, finch_req_acc ->
      Finch.Request.put_private(finch_req_acc, k, v)
    end)

    case Finch.request(finch_req, finch_name, finch_options) do
      {:ok, response} -> {req, Req.Response.new(response)}
      {:error, exception} -> {req, exception}
    end
  end)
end
```

but this becomes much more tedious with streaming requests which I don't want to rebuild or miss out on if a fellow developer decides to a stream a response (but sacrifice our telemetry), as there is a lot more that Req is doing to handle various scenarios.

The other 3 clauses branch into ~ 120 LoC that feels less reasonable to bring app-side:

https://github.com/wojtekmach/req/blob/59db3e26e3baab3b1af95c27bcc5045e5b3b0aff/lib/req/steps.ex#L699-L711

---

I'm hoping maybe we can allow an option to insert Finch private metadata, around here:
 
https://github.com/wojtekmach/req/blob/59db3e26e3baab3b1af95c27bcc5045e5b3b0aff/lib/req/steps.ex#L679-L682

I'd love to contribute a `finch_private: [] | %{}` option to the Req Finch adapter which will reduce them onto the finch request via `Finch.Request.put_private/3`, maybe around here: https://github.com/wojtekmach/req/blob/59db3e26e3baab3b1af95c27bcc5045e5b3b0aff/lib/req/steps.ex#L675-L677

This Finch request will be carried through all of the response types and be easier for Req users to catch telemetry events with custom metadata.

**Comment by wojtekmach** [comment]
Thank you for the report. I've been discussing something similar with @aselder here: https://github.com/wojtekmach/req/pull/157#issuecomment-1695601833

I think adding a :finch_private option is the way to go but I can't help but wonder if we should have something like that `finch_request: fun` which allows more flexibility e.g. if Finch adds some new things in the future we could use this callback to change these. At the same time we can start with :finch_private for sure and deprecate it down the road if something more flexible appears. So unless there are better ideas let's go with :finch_private for sure!

**Comment by aselder** [comment]
I was jsut going to work on that this week, but looks like @dbernheisel beat me to it.
