### ISSUE TITLE
use precompiled ex_brotli?

### ISSUE THREAD

**Issue by mayel** [wojtekmach/req#271]
After seeing this PR in another project: https://github.com/BeaconCMS/beacon/pull/360 I realised brotli is an optional dep of req as well and maybe could benefit from the precompiled ex_brotli too. Related to #101

**Comment by wojtekmach** [comment]
Sorry for the delay. A precompiled brotli library sounds very compelling. At the moment it's missing decoding so we can't use it in Req yet. Please send a PR when it does!
