### ISSUE TITLE
Add ability to redact custom header and option names

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#282]
Currently we redact "authorization" header and :auth option. Let's make this extensible. While at it, perhaps :redact_auth should not be an _option_ but a field on the Req struct, i.e. something more fundamental.

**Comment by wojtekmach** [comment]
We probably want to deprecate :redact_auth in favour of `redact_headers: ["authorization"]` and `redact_options: [:auth]` and when we override this, we always merge. In other words, there's no way to turn this off which is fine, people can always simply do `Map.take(req, [:headers, :options])` and see everything.

**Comment by miguel-solano** [comment]
Just opened a WIP PR for this! Hoping to get it to a good spot within the next two weeks 👍🏽
