### ISSUE TITLE
Possible infinite loop running response/error steps

### ISSUE THREAD

**Issue by rhcarvalho** [wojtekmach/req#283]
Thanks for Req!

I was working on a little plugin and realized the response and error steps can accidentally cause an infinite loop.

Considering the documented behavior for how the steps are run (error steps can cause all response steps to run and vice versa), this might be by design, in which case I apologize for the noise.

Test case / code snippet:

```elixir
  test "infinite loop" do
    req =
      Req.new()
      |> Req.Request.prepend_response_steps(
        test: fn {request, _response} ->
          IO.puts("response step")
          {request, Mint.TransportError.exception(reason: :timeout)}
        end
      )
      |> Req.Request.prepend_error_steps(
        test: fn {request, _exception} ->
          IO.puts("error step")
          {request, Req.Response.new(status: 408, body: "Timed out")}
        end
      )

    assert {:no_match} =
             req
             |> Req.get(
               url: "http://test",
               plug: fn conn ->
                 conn
                 |> Plug.Conn.send_resp(200, "OK")
               end
             )
  end
```

Perhaps a hard/safe limit on the number of steps that can be run overall, to detect/prevent accidental loops?

**Comment by wojtekmach** [comment]
Yes this is by design. FWIW there's a Req.Request.halt/1 to help with situations like that.
