### ISSUE TITLE
`decode_body`: should we gracefully handle invalid JSON?

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#295]
Currently we use Jason.decode! so on invalid JSON we crash. Should we use `Jason.decode` and return `{:error, %Jason.DecodeError{}}`?

**Comment by kzemek** [comment]
I'm here with exactly this issue, https://github.com/cloud-hypervisor/cloud-hypervisor/ API returns plaintext errors with `Content-Type: application/json`. Looks like for now I'll have to disable decoding on requests and handle body manually. It would be helpful if I was getting Req errors with proper context, so I can get to the invalid body.

**Comment by wojtekmach** [comment]
Yeah I’m afraid in your particular case you’re gonna need custom decoding anyway since you’d want to keep the error response body.

**Comment by kzemek** [comment]
I imagined the error returned by Req would contain (among other things) the response struct as-if we ran the request with `raw: true`. This would allow for graceful handling without boilerplate on user's side.

**Comment by wojtekmach** [comment]
Could you give a more concrete example how that would look like?

**Comment by kzemek** [comment]
Something like below. Note that it's wishful thinking from my PoV as the user.

```elixir
case Req.put(req(), url: "vm.boot") do
  {:ok, %Req.Response{body: body}} -> {:ok, body}
  {:error, %Req.JsonDecodeError{error: %Jason.DecodeError{}, partial_response: %Req.Response{body: body}} -> {:error, body}
end
```

Granted, this doesn't seem to be adhering to the error handling pattern you've adopted so far with mostly string-based errors, but there's some precedence with `Req.ChecksumMismatchError`.

**Comment by wojtekmach** [comment]
This sounds good, thanks. I suppose we could have a similar `%ChecksumMismatchError{response: response}` field.

We also have a feature where `http_errors: :raise` raises an error on 4xx/5xx, and that could also get a custom exception with a `:response` field but I'm not sure how to call the struct. Perhaps %Req.UnexpectedResponseError{}?

Sorry I drag you into this but I think if we're adding an `exception.response` field in one place we should standardise across the board where that makes sense.

WDYT?

**Comment by kzemek** [comment]
Absulutely, I think that standardizing on `response:` in exceptions is a great idea. For example, that's what [Python's requests lib does](https://requests.readthedocs.io/en/latest/_modules/requests/exceptions/). It also calls 4xx/5xx exceptions `HTTPError` which I think is a bit better, as `UnexpectedResponse` sounds like we were not expecting a response at all. 😄

**Comment by wojtekmach** [comment]
Good to know about requests HTTPError. I tried staying away from such name as there's a [`Mint.HTTPError`](https://hexdocs.pm/mint/Mint.HTTPError.html) and it means something completely different. Maybe it's OK that Mint.HTTPError and Req.HTTPError mean different things, otherwise there would be just one of these anyway, but not sure.

We could have `Req.{ClientError, ServerError}` but not sure it's gonna be super ergonomic to have to handle both of these.

**Comment by wojtekmach** [comment]
Closing in favour of #335.
