### ISSUE TITLE
`Req.Steps.auth/2` does not support updating authorization header

### ISSUE THREAD

**Issue by jadengis** [wojtekmach/req#297]
## Problem

I am writing a `reauthenticate` step for Req that will refresh credentials on 401.

This was not working however, and I realized that the `Req.Steps.auth/2` function uses `Req.Request.put_new_header/3` and thus cannot be used for updating the authentication on a request. Looks like this needs to be done manually. It would be nice if this was supported by the `auth/2` function out of the box. The only workaround is to just copy-paste the code from the Req library.

## Proposed Solution

Have `Req.Steps.auth/2`  support updating the authorization header.

## Versions

`:req 0.4.8`

**Comment by jadengis** [comment]
Yeah actually, I don't quite understand why `auth/2` uses `put_new_header` and not just `put_header` since `put_header` has overwrite behaviour. @wojtekmach would you be okay with making this change? I could throw together a quick PR.

**Comment by wojtekmach** [comment]
Yeah I can't think of a reason. A PR would be appreciated.

**Comment by jadengis** [comment]
@wojtekmach I put up a PR with this change.
