### ISSUE TITLE
Jason.DecodeError UTF8

### ISSUE THREAD

**Issue by leonardorame** [wojtekmach/req#298]
Hi, I'm getting this error when doing Req.get!/1:

```
Request: GET / 
** (exit) an exception was raised:
    ** (Jason.DecodeError) unexpected byte at position 542: 0xD1
```
Is there a way to avoid it?, I'm fetching a JSON that contains an "Ñ" as a value.

**Comment by wojtekmach** [comment]
Thanks for the report. You can set `decode_body: false` and manually decode the body. I'm gonna close this in favour of similar https://github.com/wojtekmach/req/issues/295.
