### ISSUE TITLE
Documentation and implementation do not align on default protocols used

### ISSUE THREAD

**Issue by LostKobrakai** [wojtekmach/req#300]
https://github.com/wojtekmach/req/blob/bfabe15f9a82d5d59b5e0ab9d514fad287861ca3/lib/req.ex#L297-L298

Documented to use both http1 and http2

https://github.com/wojtekmach/req/blob/bfabe15f9a82d5d59b5e0ab9d514fad287861ca3/lib/req/steps.ex#L983-L984

Implementation default is just http1

**Comment by wojtekmach** [comment]
Good catch, implementation is wrong and we should be sending to Finch `protocols: [:http1, :http2]` by default.

**Comment by wojtekmach** [comment]
FYI I've temporarily switched back to `protocols: [:http1]` due to https://github.com/sneako/finch/issues/265. The plan is to go back to http1+http2 once that's fixed.
