### ISSUE TITLE
Content-length header not checked for streaming body

### ISSUE THREAD

**Issue by dvic** [wojtekmach/req#318]
The docs mention `Request body streaming also works though content-length header must be explicitly set`. However, there is no error returned when you omit this header.

We've only found about this today where we hit #309 / https://github.com/sneako/finch/issues/265 and the corresponding workaround was not working. It turned out we were not passing the content-length header (with it, the workaround works just fine).

So the question is, should we reject streaming requests without a content-length header?

**Comment by dvic** [comment]
Update: setting content-length doesn't seem to affect the workaround after all, it was a flaky coincidence apparently.

Regardless, the question remains whether or not we should reject streaming requests without content-length :)

**Comment by wojtekmach** [comment]
The piece of documentation you're citing is about AWS signature and the content-length is required due to some implementation details at the moment. It's not a general requirement however and this works:

```elixir
iex> Req.put!("https://httpbin.org/anything", body: Stream.duplicate("foo", 3)).body["data"]
"foofoofoo"
```

You were hitting a different bug: https://github.com/wojtekmach/req/issues/309#issuecomment-1980934796. I just released a new version and if you upgrade you should be good to go but let me know otherwise!

**Comment by dvic** [comment]
> The piece of documentation you're citing is about AWS signature and the content-length is required due to some implementation details at the moment. It's not a general requirement however and this works:
> 
> ```elixir
> iex> Req.put!("https://httpbin.org/anything", body: Stream.duplicate("foo", 3)).body["data"]
> "foofoofoo"
> ```
> 
> You were hitting a different bug: [#309 (comment)](https://github.com/wojtekmach/req/issues/309#issuecomment-1980934796). I just released a new version and if you upgrade you should be good to go but let me know otherwise!

Ahhh clear, thanks for the quick revert fix!
