### ISSUE TITLE
(Mint.HTTPError) the given data exceeds the request window size, which is 65536.

### ISSUE THREAD

**Issue by Arsenalist** [wojtekmach/req#336]
I'm trying to use Req to upload images to FB as a base64 string, and keep getting this:

`(Mint.HTTPError) the given data exceeds the request window size, which is 65536. The server will refill the window size of the request when ready. This will be handled transparently by stream/2.`

Is there a way to significantly increase this limit so that `Req` can upload videos/images?

**Comment by wojtekmach** [comment]
Please explicitly set connect_option protocols to [:http1] or [:http2], or update to latest Req which does the former.

this bug is tracked here: https://github.com/sneako/finch/issues/265
