### ISSUE TITLE
JSON returned, but not parsed as JSON

### ISSUE THREAD

**Issue by Arsenalist** [wojtekmach/req#342]
I'm calling a few Facebook APIs and even though JSON is returned from the APIs, I'm forced to manually parse it using Jason.decode() instead of Req doing it automatically.  Basically, the value is a string of JSON instead of a Map.

`result = Req.post!("https://graph.facebook.com...").body`

This doesn't happen on all calls but some. Is there a way I can force it to decode as JSON?

**Comment by wojtekmach** [comment]
what is the content-type of responses that aren’t automatically decoded?

you can add a response step that always decodes:

```elixir
Req.new(decode_body: false)
|> Req.Request.append_response_steps(
  decode_json: fn req, resp ->
    {req, update_in(resp.body, &Jason.decode!/1}
  end
)
```

**Comment by wojtekmach** [comment]
ping

**Comment by Arsenalist** [comment]
> what is the content-type of responses that aren’t automatically decoded?
> 
> you can add a response step that always decodes:
> 
> ```elixir
> Req.new(decode_body: false)
> |> Req.Request.append_response_steps(
>   decode_json: fn req, resp ->
>     {req, update_in(resp.body, &Jason.decode!/1}
>   end
> )
> ```

Sorry about the delay. Thank you for this approach. I'm using Meta's Marketing API and though JSON is returned, it doesn't seem to parse it. The content-header is `application/json`. However, doing what you suggested works fine. Thank you.

**Comment by caioaao** [comment]
I'm also experiencing this, in version 0.5.8. I also checked that the content type is application/json (more specifically `"content-type" => ["application/json; charset=utf-8"]`, and only happens once every 30 or so requests

**Comment by wojtekmach** [comment]
@caioaao can you share anything else about the response? What's the status code? Did it happen after a redirect or a retry?

**Comment by caioaao** [comment]
Sure! This is most of the response (omitting part of the body since it's a production payload):

```elixir
 %Req.Response{
    status: 200,
    headers: %{
      "cache-control" => ["max-age=0, no-cache, no-store"],
      "connection" => ["keep-alive"],
      "content-length" => ["2518"],
      "content-type" => ["application/json; charset=utf-8"],
      "date" => ["Thu, 16 Jan 2025 21:03:57 GMT"],
      "expires" => ["Thu, 16 Jan 2025 21:03:57 GMT"],
      "pragma" => ["no-cache"],
      "server" => ["nginx"],
      "x-client-tls-ver" => ["tls1.3"],
    },
    body: "{\r\n  \"Id\": \"633f124f-f1e9-417c-823a-b60bb674cc40\",\r\n  \"Status\": \"OK\",\r\n}",
  }
```

I also compared the response that didn't decode the body with ones that did and couldn't find any relevant differences. I do think it happened after a retry though

**Comment by wojtekmach** [comment]
Thank you. This looks correct so yeah, not sure what's going on.

**Comment by caioaao** [comment]
Could the issue be related to this line? https://github.com/wojtekmach/req/blob/67c5b9d3f5dac275dfa530f2df13a79184d6d2c2/lib/req/steps.ex#L2171 It seems like if we retry a request, we halt the steps pipeline, even if it succeeds

**Comment by wojtekmach** [comment]
I don't think that's it, the line above would have run the request and all the request and response steps would run then.

We can see it behaving correctly here:

```elixir
Mix.install([:req, :plug])

{:ok, _} = Agent.start_link(fn -> 1 end, name: :counter)

Req.get!(
  plug: fn conn ->
    count = Agent.get_and_update(:counter, &{&1, &1 + 1})

    if count > 2 do
      Req.Test.json(conn, %{status: :ok})
    else
      Req.Test.json(%{conn | status: 500}, %{message: :oops})
    end
  end,
  retry_delay: 0
)
|> then(&dbg(&1.body))
```

**Comment by caioaao** [comment]
Ok, then I'm lost too! 😅 I set `retry: false` in our code and started
doing the retry manually outside of req's pipeline and that fixed it for us
- no more unparsed JSON bodies

Oh, another thing: we were using a custom `retry?` function, if it helps

Em qui., 16 de jan. de 2025 às 19:15, Wojtek Mach ***@***.***>
escreveu:

**Comment by wojtekmach** [comment]
could you share your custom function? If not, could you send it to me privately?

**Comment by caioaao** [comment]
I think I narrowed it down: it might be due to a step that calls `Req.Request.halt()` with a retriable error. Here's a script that reproduces the issue:

```elixir
Mix.install([:req, :plug])

successful_response = Req.Response.new(
  status: 200,
  body: :json.encode(%{message: "ok"}) |> IO.iodata_to_binary(),
  headers: %{"content-type" => ["application/json"]})

Req.get!("http://example.com",
  adapter: fn request -> 
      { request, successful_response }
end)
|> tap(&dbg(&1.body))

{:ok, _} = Agent.start_link(fn -> 1 end, name: :counter)
Req.get!("http://example.com",
  adapter: fn request -> 
    count = Agent.get_and_update(:counter, &{&1, &1 + 1})
    if count > 2 do
      { request, successful_response }
    else
      Req.Request.halt(request, Req.Response.new(status: 500))
    end
end)
|> tap(&dbg(&1.body))
```

Even though the successful response is the same, only the first one returns the correct body:

```
$ elixir tmp/req_342.exs
[tmp/req_342.exs:13: (file)]
capture.body #=> %{"message" => "ok"}


10:42:39.165 [warning] retry: got response with status 500, will retry in 1000ms, 3 attempts left

10:42:40.167 [warning] retry: got response with status 500, will retry in 2000ms, 2 attempts left
[tmp/req_342.exs:24: (file)]
capture.body #=> "{\"message\":\"ok\"}"
```

**Comment by wojtekmach** [comment]
That is expected, if we halt we don’t run any steps anymore. Do you have a custom step that halts?

**Comment by caioaao** [comment]
Ah, nice, so just a misunderstanding on my end! Yes, we do have a step that checks a [token bucket](https://en.wikipedia.org/wiki/Token_bucket) before making a request to limit calls. Something like this:

```elixir
  def check_rate_limit(request) do
    if rate_limited?(request) do
      Req.Request.halt(
        request,
        ApiError.exception(message: "Token not available")
      )
    else
      request
    end
  end
```

In this case, should I have just returned a `{request, error}`?
