### ISSUE TITLE
Response .json keys as Atoms

### ISSUE THREAD

**Issue by shotleybuilder** [wojtekmach/req#347]
Is there a way to have the response use atoms and not strings as the keys in the response?
Or should I look to post-process the response and do the conversion outside of Req?

**Comment by shotleybuilder** [comment]
Okay, not such a good idea to have this as part of Req since atoms are not garbage collected.  I can do this post-request.

**Comment by wojtekmach** [comment]
You can use :decode_json to pass option down to Jason, see https://hexdocs.pm/req/Req.Steps.html.
