### ISSUE TITLE
Pluggable caching system?

### ISSUE THREAD

**Issue by thbar** [wojtekmach/req#36]
Thanks for `req`! I love it.

The `if_modified_since/2` caching is nice, but not all servers implement it correctly.

At times, within LiveBook for instance, I would like to be able to:
- cache for 1 day, no matter the result, as long as it is a 200
- cache based on some custom logic

I wonder if something could be done to have something pluggable that would let the user add a step, just like `if_modified_since/2`, but with custom logic.

Maybe it is already doable, I don't know yet! I wonder what your thoughts on that are.

**Comment by thbar** [comment]
I have read in more details the readme, I believe what is there is already sufficient to let me implement custom steps.

I will re-open if that's not the case, and will share examples of alternate caching maybe!

**Comment by wojtekmach** [comment]
Yup the existing cache solution is just a regular step, there's nothing special about it. You can build your own. If you run any issues, feel free to comment here or elsewhere and I'll be happy to help. Just fyi, I have very limited availability this month but happy to get to it in October :)

**Comment by thbar** [comment]
Thanks for the feedback! It was ultimately easy to get at least something (not as nice as `if_modified_since/2` at this point, I don't use `prepend_actions` and such yet). I am sharing it in case it helps others later (but I know how to improve it already, not asking for feedback on this!):

```elixir
defmodule DiskCache do
  @moduledoc """
  A very quick simple disk-cache, persisting everything to disk
  as long as it responds with HTTP 200.
  TODO: use Req low-level API https://github.com/wojtekmach/req#low-level-api
  or use similar nicer design.
  """
  def disk_cache(request, dir \\ "data") do
    unless File.exists?(dir), do: File.mkdir_p!(dir)
    cache_file = Path.join(dir, build_cache_key(request.uri |> URI.to_string()))

    if File.exists?(cache_file) do
      cache_file |> File.read!() |> :erlang.binary_to_term()
    else
      response = request |> Req.run!()
      File.write!(cache_file, :erlang.term_to_binary(response))
      response
    end
  end

  def build_cache_key(url) do
    Regex.replace(~r/\W/, url, "-")
  end
end
```

I will maybe share a PR (with better code, this is just a quick implementation) for examples or something later.
