### ISSUE TITLE
Would it make sense to default `:retry_log_level` to `:warning`?

### ISSUE THREAD

**Issue by jozuas** [wojtekmach/req#369]
I'm aware https://github.com/wojtekmach/req/issues/357, but while that's in the process of consideration, would it make sense to default `:retry_log_level` to `:warning`?

In my view, transient networking issues are expected, and with the default retry behaviour recoverable. What should be an error is if the retries eventually failing, not each individual retry step.

**Comment by wojtekmach** [comment]
Good call, a PR would be appreciated.
