### ISSUE TITLE
Block Req network calls in tests

### ISSUE THREAD

**Issue by mxgrn** [wojtekmach/req#398]
Context: I use Mimic to stub my HTTP clients, so, I'm not (yet) using Req's testing capabilities.

Is there a simple way to block all Req network calls at once, during tests?

**Comment by wojtekmach** [comment]
Req supports custom adapters and so I believe the easiest way is to have an adapter that fails when it is about to make the network call.

The two most common solutions are:

  1. Use env-specific Req configuration:

     ```elixir
     # lib/foo.ex
     defmodule Foo do
       def request(options) do
         Req.new(Application.fetch_env!(:myapp, :foo_req_options))
         |> Req.request(options)
       end
     end
     ```

     And then in your `config/test.exs` you can:

     ```elixir
     adapter = fn _req -> raise "no network calls in tests!" end
     config :myapp, foo_req_options: [adapter: adapter]
     ```

  2. In `config/test.exs` or `test/test_helper.exs` do:

     ```elixir
     adapter = fn _req -> raise "no network calls in tests!" end
     Req.default_options(adapter: adapter)
     ```

The latter uses the global Req configuration so as a side benefit it will work for all Req clients you might be using.

Btw in the future please ask questions on elixirforum and similar and feel free to cc me. I believe this way the answers will be more discoverable to more people.

**Comment by wojtekmach** [comment]
cc @dbernheisel, I believe you asked me once something along these lines. If we can improve things, lmk!
