### ISSUE TITLE
HTTP errors and checking checksums

### ISSUE THREAD

**Issue by fhunleth** [wojtekmach/req#399]
I'm not sure if I'm doing this the intended way so I'm not 100% sure this is an issue.

I'm using the `:checksum` option to verify SHA256s. It turns out that I got the URL wrong and received a checksum error on the 404 error message. It took me a while to figure out that the checksum error wasn't due to the file being corrupt, but that it had to do with a URL typo. I was thinking that using `http_errors: :raise` might cause the 404 to be raised instead of the checksum mismatch. It looks like the checksum is evaluated first, though:

```elixir
iex> Req.get!("https://httpbin.org/not_json", checksum: "sha1:9274ffd9cf273d4a008750f44540c4c5d4c8227c")
** (Req.ChecksumMismatchError) checksum mismatch
expected: sha1:9274ffd9cf273d4a008750f44540c4c5d4c8227c
actual:   sha1:c40de9ff0eb1a8adb68dcd7266d2e5c8f3610e8c
    (req 0.5.4) lib/req.ex:1092: Req.request!/2
    iex:3: (file)
iex> Req.get!("https://httpbin.org/not_json", checksum: "sha1:9274ffd9cf273d4a008750f44540c4c5d4c8227c", http_errors: :raise)
** (Req.ChecksumMismatchError) checksum mismatch
expected: sha1:9274ffd9cf273d4a008750f44540c4c5d4c8227c
actual:   sha1:c40de9ff0eb1a8adb68dcd7266d2e5c8f3610e8c
    (req 0.5.4) lib/req.ex:1092: Req.request!/2
    iex:3: (file)
```

Is this intended behavior?

**Comment by wojtekmach** [comment]
Good catch, I moved handle_http_errors to be earlier. I should have a new release next week or so.

**Comment by fhunleth** [comment]
That was super fast. Thank you!!!!

**Comment by wojtekmach** [comment]
v0.5.6 is out with the fix, thanks again for the report!
