### ISSUE TITLE
Please how do we limit total-request/ response time?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [wojtekmach/req#427]
Please how do we limit the total request/response time to a fixed value?

This below does not work in limiting the total request/respose time

`Req.get!("https://httpbin.org", connect_options: [timeout: 2000])`

**Comment by wojtekmach** [comment]
At the moment the best option is to wrap your Req call in `Task.async(fun) |> Task.await(timeout)`. This is not good enough obviously, we will improve it, it's being tracked in https://github.com/wojtekmach/req/issues/428.
