### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#44]
Currently we have two ways of making requests, the high- and low-level API:

```elixir
Req.get(url)

Req.build(:get, url)
|> Req.prepend_default_steps()
|> Req.run()
```

We can extend Req by adding steps which is possible with the low-evel API. However, given we build-up the request pipeline starting with the method and the URL, the resulting struct isn't ideal to re-use for different invocations. (It doesn't hurt, but it somewhat feels dirty to then overwrite the method, the URL, etc.)

A simple change is to move things around. Instead of `build/2 + run/0` we have `build/0 + run/3`:

```elixir
Req.build()
|> Req.prepend_default_steps()
|> Req.run(:get, url)
```

Then there's also the plugins API proposal, https://github.com/wojtekmach/req/pull/35. The idea was to encapsulate some common logic but more importantly make it super easy to use, without building up the request pipeline. Plugins are modules so we can very easily refer to them but then again from the day one we wanted to avoid modules in favour of anonymous functions or MFArgs, the steps. So plugins shouldn't cover for the limitations of the api, instead it should be more straightforward to achieve things with just steps, and then plugins are just sugar.

Finally we also have https://github.com/wojtekmach/req/issues/34.

Putting this all together, I'm now thinking about this API:

```elixir
# high-level

Req.get!(url)

Req.new()
|> Req.get!(url)

# low-level

Req.Request.new()
|> Req.Request.prepend_request_steps(...)
|> Req.Request.run()

# mix of high- and low-level

Req.new()
|> Req.Request.prepend_request_steps(...)
|> then(&IO.inspect/1)
|> Req.get!(url)
```

and regarding plugins we can do either or both:

```elixir
Req.get!(url, plugins: [ReqS3])

Req.new()
|> ReqS3.call()
|> get!(url)
```

To sum up, we'd add these functions:

```elixir
Req.new(options \\ [])
Req.get!(request, url, options)
```

We'd rename these:

```
Req.build/1 -> Req.Request.new/1
Req.{append,prepend}_{request, response,error}_steps -> Req.Response.*
```

and remove `Req.prepend_default_steps` in favour of `Req.new/1`. `Req.new` is basically `Req.Request.new + prepend_default_steps`.

With this, the `get` function and friends will become a bit more complicated now:

```elixir
def get(url) when is_binary(url)

def get(url, options) when is_binary(url) and is_list(options)

def get(%Req.Request{} = request, url, options) when is_binary(url) and is_list(options)
```

Another complication is this. Lets say we want to enable `retry` and `cache` steps. We'll be able to do it in two places now:

```elixir
Req.get(url, retry: true, cache: true)

Req.new(retry: true) |> Req.get!(url, cache: true)
```

So basically on `Req.new` we'd add all the default steps + the opt-in ones based on the options. On Req.get/2 we'd do the same. On Req.get/3 we'd additionally opt-in steps per options.

SO yeah it might be a bit complicated but I think it is still reasonable enough.

WDYT?

**Comment by wojtekmach** [comment]
Hm, another idea is this:

```elixir
Req.new(retry: true) #=> %Req.Request{options: [retry: true], request_steps: [], error_steps: [], ...}
|> Req.get!(url)     # prepends defaults steps and executes the pipeline
```

That is, `Req.new/1` accepts all the options we currently have, but it doesn't yet add any steps. Only when we execute the pipeline with `get!`, `post!`, `request!`, etc, the default steps (decompress, decode, etc) are prepended. I think this greatly simplifies this:

> So basically on Req.new we'd add all the default steps + the opt-in ones based on the options. On Req.get/2 we'd do the same. On Req.get/3 we'd additionally opt-in steps per options.

which I wasn't so sure about.

**Comment by jonatanklosko** [comment]
Regarding the last idea, then the question is whether `Req.run!()` should honor the options or not, options belong to the high level, but what if someone does `Req.new(retry: true) |> Req.run!(:get, url)`

**Comment by wojtekmach** [comment]
I think `Req.run!` would be renamed to `Req.Request.run!` and it would no longer honour options like `:retry`, `:cache`, etc.

I think this is roughly what I have in mind:

```elixir
defmodule Req.Request do
  defstruct [
    :method,
    :url,
    headers: [],
    body: "",
    options: [],
    request_steps: [],
    response_steps: [],
    error_steps: []
  ]

  def new(options \\ []) do
    struct!(__MODULE__, options)
  end

  def run!(request) do
    run_request(request)
  end

  defp run_request_steps(request) do
    Enum.reduce_while(request.request_steps, request, ...)
  end

  defp run_response_steps(request, response) do
    Enum.reduce_while(request.request_steps, {request, response}, ...)
  end

  defp run_error_steps(request, exception) do
    Enum.reduce_while(request.error_steps, {request, exception}, ...)
  end
end

defmodule Req do
  def new(options \\ []) do
    Req.Request.new(options: options)
  end

  def get!(request \\ %Req.Request{}, url, options \\ []) do
    request!(request, [method: :get, url: url] ++ options)
  end

  def request!(request \\ %Req.Request{}, options \\ []) do
    {method, options} = Keyword.pop!(options, :method)
    {url, options} = Keyword.pop!(options, :url)
    {body, options} = Keyword.pop!(options, :body, "")
    {headers, options} = Keyword.pop!(options, :headers, [])

    %{request | method: method, url: url, body: body, headers: headers, options: options}
    |> prepend_default_steps()
    |> Req.Request.run!()
  end

  @doc api: :response
  def decompress(request) do
    ...
  end

  defp prepend_default_steps(request) do
    ...
  end
end
```

wdyt?

**Comment by wojtekmach** [comment]
There were two major goals of this, conveniently building up a request pipeline to be reused elsewhere and having support for plugins. I believe we achieved the former with `Req.default_options/1` (which is global so not as nice as passing a data structure around) and the latter with `Req.run_steps/2`. Here's a couple examples:

Default options:

```elixir
Mix.install([
  {:req, "~> 0.2.0"},
  {:req_s3, github: "wojtekmach/req_s3"}
])

Req.default_options(base_url: "https://api.github.com/repos/elixir-lang/elixir")

Req.get!("").body["description"]
|> IO.inspect()

# Outputs:
# "Elixir is a dynamic, functional language designed for building scalable and maintainable applications"

Req.get!("/issues").body
|> Enum.map(& &1["title"])
|> Enum.filter(&(&1 =~ "Support Erlang/OTP"))
|> IO.inspect()

# Outputs:
# ["Support Erlang/OTP 25 new features", "Support Erlang/OTP 24 new features",
#  "Support Erlang/OTP 23 new features"]
```

"Plugins" (just steps!)

```elixir
Req.get!("s3://ossci-datasets/", steps: [ReqS3]).body
|> IO.inspect()

# Outputs:
# ["mnist/", "mnist/t10k-images-idx3-ubyte.gz", "mnist/t10k-labels-idx1-ubyte.gz",
#  "mnist/train-images-idx3-ubyte.gz", "mnist/train-labels-idx1-ubyte.gz"]

body = Req.get!("s3://ossci-datasets/mnist/train-images-idx3-ubyte.gz", steps: [ReqS3]).body
<<_::32, n_images::32, n_rows::32, n_cols::32, _body::binary>> = body

{n_images, n_rows, n_cols}
|> IO.inspect()

# Outputs:
# {60000, 28, 28}
```

**Comment by wojtekmach** [comment]
See https://github.com/wojtekmach/req/pull/88 for another stab at this/ In a nutshell we can now do: `Req.new(base_url: base_url) |> Req.request(url: url) and similar`!
