### ISSUE TITLE
`auth`: Add `:netrc | {:netrc, path}` as possible values

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#52]
Instead of having a distinct load_netrc step, make it an option to auth, e.g.: `auth: :netrc` which also would be the default?

**Comment by wojtekmach** [comment]
Let's still keep it as a distinct step, it's just auth/2 is going to use it under the hood.

**Comment by srowley** [comment]
Looking at this, I am not sure why keeping `load_netrc` as a step is desirable. Could you confirm?

If you run both steps, it will send two authorization headers, which I believe is not consistent with [RFC7230](https://www.rfc-editor.org/rfc/rfc7230#section-3.2.2).

It makes sense to me to keep `load_netrc` as a private function to run under the hood - maybe this was the intent?

**Comment by srowley** [comment]
Separate question - `load_netrc` seems to be looking for a file with lines like:
```
machine localhost
username foo
password bar
```

But the documentation I can find [here](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) and [here ](https://everything.curl.dev/usingcurl/netrc)suggests it should be:

```
machine localhost
login foo
password bar
```

or 

`machine localhost login foo password bar`

Should I stick with `username` or use `login`?

**Comment by wojtekmach** [comment]
oops, it should have been `login`, thanks!
