### ISSUE TITLE
configurable default steps

### ISSUE THREAD

**Issue by princemaple** [wojtekmach/req#55]
something like `default_options` that permanently modifies what "default steps" are.

Maybe? Not sure if it's a good idea.

**Comment by wojtekmach** [comment]
This is what `default_options` already does. Using options we can opt-in to steps (e.g. `:auth` option) or add even more steps (`:steps` option). We could allow opting-out of steps, e.g. `follow_redirects: false` but I didn't have a need for that yet.

Could you give some more details about your use case?

**Comment by princemaple** [comment]
Yeah I realized later that default_options already does it. Posted as I was thinking. 🙏
