### ISSUE TITLE
per process default options

### ISSUE THREAD

**Issue by princemaple** [wojtekmach/req#56]
If I have several long running gen servers that use `req`, they may need different base urls.

Well, I could just write a build function that loads base url from process state/dictionary and returns a basic request for further customization. Feel free to close.

**Comment by wojtekmach** [comment]
> Well, I could just write a build function that loads base url from process state/dictionary and returns a basic request for further customization.

Yeah, I'd do that. Per-process options have major tradeoffs in terms of ergonomics so no plans to pursue that yet.
