### ISSUE TITLE
function typespecs

### ISSUE THREAD

**Issue by princemaple** [wojtekmach/req#57]

**Comment by wojtekmach** [comment]
if you'd like to send a PR, that'd be appreciated, but I don't plan to work on this myself at the moment. The thing is, most of the functions here are steps and thus the specs would be rather boring: `@spec some_request_step(request) :: request`. :-)

**Comment by princemaple** [comment]
I thought you could mark it as `need help` or something so someone would pick it up.

Yeah I think I'd send a PR to spec the highlevel functions at least. I was stuck for a second that I didn't know what the return type of the function was :)
