### ISSUE TITLE
New step: `run_plug`

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#61]
Example:

```elixir
defmodule Foo do
  def init(opts), do: opts

  def call(conn) do
    Plug.Conn.send_resp(conn, 200, "foo")
  end
end

iex> Req.get("http://foo/bar", plug: Foo).body
"foo"
```

See https://www.python-httpx.org/advanced/#calling-into-python-web-apps

**Comment by maxxst** [comment]
I was wondering: should we try to "plugify" the req library even more?

1st thougt would be to populate the [Plug.Conn Request Fields](https://hexdocs.pm/plug/Plug.Conn.html#module-request-fields) using the steps and then make the request to populate the [Response Fields](https://hexdocs.pm/plug/Plug.Conn.html#module-response-fields)

```elixir
conn = Req.build(base: "https://example.com/")
  |> get("foo.html")  # evaluates to example.com/foo.html
```

would return a [Plug.Conn](https://hexdocs.pm/plug/Plug.Conn.html)

```elixir
case conn do
  %Plug.Conn{status: 200, resp_body: body} -> IO.inspect(body)
  %Plug.Conn{status: status, resp_body: body} -> 
    IO.puts("Error #{status})
    IO.inspect(body)
end
```

See https://hexdocs.pm/plug/Plug.Conn.html

**Comment by wojtekmach** [comment]
My initial thought is not to move forward with it because I'd rather not add another dependency. We'd never use any _plugs_. We'd not use `secret_key_base` or `state` fields from the `Plug.Conn` struct. But all the other Conn fields actually seem like a good fit.

What do you think are pros and cons of moving forward with this?

**Comment by maxxst** [comment]
The main benefit for me would be to just keep thinking in a connection, if people are used to `Plug.Conn` in the context of phoenix for example it might be easier understand (or use) established concepts.

For my specific use-case: I want to build a phoenix app that consumes one or two APIs, works with the data, and displays the data I need. The thought of 'merging' different connections into that one I want to return is somewhat appealing.

**Comment by wojtekmach** [comment]
Gotcha. Can you think of any downside of moving forward with this?

**Comment by maxxst** [comment]
After playing around with plug a little bit more I would propose the following:

- combine `%Req.Request{}` & `%Req.Response{}` into a `%Req.Conn{}`. 
- Use the fieldnames and types of `%Plug.Conn{}` where possible
- add a converter `%Req.Conn{}` -> `%Plug.Conn{}`

**Comment by wojtekmach** [comment]
I have given it some thought and at the moment I think that while increased familiarity would be very nice it does not outweigh the downside of bringing in an extra dependency of Plug. A minor downside is the current return value, `Req.Response`, is much more useful the vast majority of the time than a structure that also contains request stuff. Though as the _intermediate_ data structure, `Req.Conn` sounds pretty appealing given all steps would take it (currently response steps take `{req, resp}`, similar for error steps.)

So yeah, let's leave things as is. Thank you for the proposal!
