### ISSUE TITLE
`follow_redirects`: Add `:max_redirects` option

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#64]

**Comment by aleDsz** [comment]
Should it have a `:redirect_delay` like retry does?

**Comment by wojtekmach** [comment]
I don't think so, why would we want to wait?

**Comment by aleDsz** [comment]
Maybe the host that we are making the request could have some protection against multiple requests in the same time

**Comment by wojtekmach** [comment]
I see, fair enough. Let's not worry about this at the moment, can always address it later.
