### ISSUE TITLE
New step: `put_files`

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#74]

**Comment by wojtekmach** [comment]
See https://github.com/elixir-mint/mint/issues/232

**Comment by zolrath** [comment]
I've just come across a need for this. With mint deciding against adding the feature, is it effectively dead here as well?

**Comment by wojtekmach** [comment]
Not dead, the issue was about sendfile-based optimisation.

**Comment by wojtekmach** [comment]
I'm not planning to add this in the short term but further discussion and PRs are welcome!
