### ISSUE TITLE
OpenTelemetry support

### ISSUE THREAD

**Issue by dvic** [wojtekmach/req#87]
Hi!

Is there interest for (optional) OpenTelemetry support for this library? I've currently written a wrapping adapter that might prove useful (see a gist of it below). We could check if the OpenTelemetry library is loaded and enable the functionality if the `opentelemetry_tracing` option is set to `true`? Let me know and if needed I can submit a PR :) 

```elixir
defmodule ReqExt.OpenTelemetry do
  require OpenTelemetry.Tracer

  def trace_adapter(%Req.Request{} = request_arg) do
    Req.Request.put_adapter(request_arg, fn request ->
      http_method = http_method_to_string(request.method)

      attributes = %{
        "http.method": http_method,
        "http.url": URI.to_string(request.url),
        "http.target": request.url.path,
        "http.host": request.url.host,
        "http.scheme": request.url.scheme,
        "net.peer.port": request.url.port
      }

      OpenTelemetry.Tracer.with_span "HTTP #{http_method}", %{
        kind: :client,
        attributes: attributes
      } do
        {request, response_or_exception} = Req.Steps.run_steps(request, [request_arg.adapter])

        handle_response_or_exception(response_or_exception)
        {request, response_or_exception}
      end
    end)
  end

  defp handle_response_or_exception(%Req.Response{} = response) do
    OpenTelemetry.Tracer.set_attribute(:"http.status_code", response.status)

    if response.status >= 400 do
      OpenTelemetry.Tracer.set_status(OpenTelemetry.status(:error))
    end
  end

  defp handle_response_or_exception(%{__exception__: true} = exception) do
    message = Exception.format_banner(:error, exception)

    OpenTelemetry.Tracer.set_status(OpenTelemetry.status(:error, message))
  end

  defp http_method_to_string(method) when is_atom(method) do
    Atom.to_string(method) |> String.upcase()
  end

  defp http_method_to_string(method) when is_binary(method) do
    method
  end
end
```

**Comment by wojtekmach** [comment]
The default adapter, Finch, is already using telemetry. If there was an easy way to bridge Finch's telemetry and open telemetry, would that be enough for your use case?

**Comment by dvic** [comment]
I was working already on that as well but currently it's difficult to have a 'start' and 'end' for a finch request. It's scattered across different `connect`, `queue`, `request`, and `response` telemetry events. While this is useful to capture detailed information of the execution of a request, it's difficult to capture an OpenTelemetry span. For example, a `nxdomain` error is emitted as part of the `connect` event, but this event is not always emitted of course because of pooling.

Thinking about it now, it might be useful to open an issue on the Finch repo to see if the above issue can be solved easily, e.g., by providing a common telemetry event for all different kind of requests/responses (http1/http2, success/failure).

**Comment by wojtekmach** [comment]
Yes, I think the Finch team would be interested in instrumentation improvements. If some of these events would not make sense in Finch, I'm happy to revisit it here. Since Req can easily use other underlying adapters, maybe Req should emit its own telemetry events but let's wait for some more use cases.

**Comment by dvic** [comment]
Makes sense, I'll reach out to the FInch team to see if we can improve things there!

**Comment by wojtekmach** [comment]
Since the Finch PR got merged in I assume we're good here but please let me know otherwise. Thanks for your contribution!

**Comment by tsloughter** [comment]
Basing support on finch telemetry events means it is tied to finch, instead of the pluggable req, and it puts extra work on the user to propagate trace context in their request (since the headers can't be updated by a telemetry event handler).

Certainly doesn't need to be builtin to Req itself -- not that that would be a bad thing :) -- but I think we need one in OpenTelemetry's instrumentation libraries, along with finch https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/115

**Comment by tsloughter** [comment]
Realized it actually isn't possible to propagate the context properly when relying on telemetry events.

**Comment by wojtekmach** [comment]
@tsloughter thanks for extra context. If there's OT support for Finch then I'd say it's not ideal but good enough for Req at the moment. While we have pluggable adapters FWIW they're mostly used for testing and are a logical step of the extensible design. I don't really expect people _not_ to run Finch under the hood in the wild. (Though I am tempted to support Mint out of the box for rare situations where Finch is an overkill but then again Req is probably an overkill as well. :))

**Comment by tsloughter** [comment]
@wojtekmach I don't think there will/can be Finch support for context propagation because it has no concept of middlewares, while the clients built on top of it do. So it has to be done by each of those clients built on Finch.
