### ISSUE TITLE
Request streaming

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#9]

**Comment by zachallaun** [comment]
When using the default Finch adapter, isn’t this already supported by setting body to a `{:stream, stream}` tuple? Should this just be explicitly tested/documented and added as an optional part of the adapter interface? (Could say that custom adapters that support streaming should look for the same tuple.)

[Relevant docs from Finch](https://hexdocs.pm/finch/Finch.html#build/5)

**Comment by wojtekmach** [comment]
Yup, it mostly just works. The only problem I'm aware is this:

```elixir
iex> Req.post!("http://httpbin.org/anything", body: {:stream, ~w(a b c d)}, compress_body: true).body
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an iodata term

    (erts 14.0.1) :erlang.iolist_to_iovec({:stream, ["a", "b", "c", "d"]})
    (erts 14.0.1) :zlib.enqueue_input/2
    (erts 14.0.1) :zlib.deflate/3
    (erts 14.0.1) :zlib.gzip/1
    (elixir 1.16.0-dev) lib/map.ex:916: Map.update!/3
    (req 0.3.9) lib/req/steps.ex:510: Req.Steps.compress_body/1
    (req 0.3.9) lib/req/request.ex:680: Req.Request.run_request/1
    iex:4: (file)
```

but it should be fairly straightforward to fix.

**Comment by wojtekmach** [comment]
Closing in favour of #219.
